### ISSUE TITLE
Issue with emails sent by Intel

### ISSUE THREAD

**Issue by Zero3K** [the-djmaze/snappymail#1050]
![Intel - SnappyMail](https://user-images.githubusercontent.com/6194332/227225595-794b9748-b749-41f9-98d4-07e47d9b2ede.png)
![Intel - mboxview](https://user-images.githubusercontent.com/6194332/227225634-53b72cca-9268-4410-873d-081c06d2d2db.png)
[Intel account email verification code.eml.txt](https://github.com/the-djmaze/snappymail/files/11051573/Intel.account.email.verification.code.eml.txt)

**Comment by the-djmaze** [comment]
Correct. The HTML structure is:
```
<td width="50%">
<td>content
<td width="50%">
```
Since 100% is max and the first and third combined is 100% there is nothing left for the second TD.
But, they want to force the second to be 640px like:
```
<td width="50%">
<td><table width="640"
<td width="50%">
```

Since SnappyMail tries to be responsive this is a conflict because SnappyMail makes it:
```
<td width="50%">
<td><table style="max-width:640px"
<td width="50%">
```

SnappyMail can't solve this, but Intel can solve this with:
```
<center>
<table width="640"
```
or
```
<div style="text-align: center">
<table width="640"
```
