### ISSUE TITLE
Issue with confirmation email from Data Annotation

### ISSUE THREAD

**Issue by Zero3K** [the-djmaze/snappymail#1125]
![DataAnnotation - SnappyMail](https://github.com/the-djmaze/snappymail/assets/6194332/e8f76ba0-454f-444c-9f88-e8b86573471f)
![DataAnnotation - mboxview](https://github.com/the-djmaze/snappymail/assets/6194332/439d188c-a757-41f0-a9fc-9939c6fde356)
[Confirm your dataannotation.tech account.eml.txt](https://github.com/the-djmaze/snappymail/files/11437562/Confirm.your.dataannotation.tech.account.eml.txt)

**Comment by the-djmaze** [comment]
Correct. The mail uses
```html
    <a style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; text-decoration: none; color: #265cc4;">
        <button class="btn-confirm" style='-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; gap: 8px; min-width: 143px; height: 44px; background-color: #265cc4; box-shadow: 0px 1px 2px rgba(16,24,40,0.05); border-radius: 8px; font-family: "Inter", sans-serif; font-style: normal; font-weight: 500; font-size: 1em; line-height: 24px; color: #fff; cursor: pointer; padding: 10px 18px; border: 1px solid #265cc4;'>
            Confirm account
        </button>
    </a>
```

The problem here is that BUTTON is an HTMLElement that should be inside FORM.
E-mails don't process forms so i disallowed all form input HTML elements.
https://github.com/the-djmaze/snappymail/blob/2c014caa725c04f20a5dde77f0e02d535042602d/dev/Common/Html.js#L17-L23

This could be improved by keeping the innerHTML
