### ISSUE TITLE
Attachments within the .eml file.

### ISSUE THREAD

**Issue by pepemadalena** [the-djmaze/snappymail#1166]
**Is your feature request related to a problem? Please describe.**
The attachments within the .eml file cannot be viewed using the "eml viewer."
I am using Nextcloud version 26.0.2 and SnappyMail 2.28.1.

**Describe the solution you'd like**
Within the eml viewer, include a link to the attachments contained in the "eml" file.

**Describe alternatives you've considered**

Thanks

**Comment by the-djmaze** [comment]
EML viewer uses the existing message "View in separate window" (and for printing).
The existing viewer is a slight modified version of the original RainLoop code and therefore can not and does not control attachments.
This is due to the fact that it generates the HTML in a new window/tab without JavaScript controls.

See https://github.com/the-djmaze/snappymail/blob/b8ebe6c1bc8e0caed112c8ecc7f469899d979880/dev/Model/Message.js#L339-L364

Which uses
https://github.com/the-djmaze/snappymail/blob/master/dev/Html/PreviewMessage.html

To achieve what you want, the EML view could be changed to use the current message view pane in the main window (and replace the current message with the EML).
But this would also require to solve several issues/complications.

Another option would be to re-use the MessageView code and put that in a `<dialog>` element as "popup".
https://github.com/the-djmaze/snappymail/blob/master/dev/View/User/MailBox/MessageView.js

This could be written as plugin or other feature.

**Comment by pepemadalena** [comment]
Hi,
In case it can help, I'll describe the operation of the Horde imp application. When you double-click on the email message, it opens a new tab with the complete message, allowing you to reply, view attachments, and so on.
You can view a simulation at http://demo.horde.org/.
This option provides a lot of power to email management, as it allows you to have multiple windows open for composing and managing emails.
Thanks

**Comment by the-djmaze** [comment]
I understand, but Horde works completely different.
It just opens a complete new URL as `demo.horde.org/imp/dynamic.php?page=message&...` and then loads the email body, CSS, JS etc. etc.

SnappyMail does not do this because it already downloaded the email body and sees no use for doing this again (this prevents bandwidth usage and server usage).

I've made a slight modification that maybe helps to support attachments.
Feel free to test in next release.

**Comment by pepemadalena** [comment]
Thank you very much.
