### ISSUE TITLE
Issues with color picker

### ISSUE THREAD

**Issue by jmrapin81** [the-djmaze/snappymail#1199]
**Describe the bug**
using Snappy Mail with Nextcloud, I cannot change the font color or the background color. I cannot work out this feature. I am surprised I am the first one to report this as it has been an issue for me for a while.

**To Reproduce**
Steps to reproduce the behaviour:
1. Write a new email. Type some text. 
2. Highlight some text to change its colour. 
3. Click on the colour picker (font colour or backgroud colour same problem) . Choose a colour 
4. Colour not applied to text.

Errors 
1) When the colour picker is open the text selection is gone. Therefore cannot change colour. This is very annoying as I usually format the text once I am done with the content. Al;so this means you cannot change the colour once the text is typed. That's not usable IMO
2) When colour is chosen, how to validate the colour? There is no OK button, apply etc. to close the colour picker.
3) Even if no text is selected choosing a colour is not applied to the location the cursor is.

How to reproduce bug 3)
1) open a new mail
2) insert a few blank lines at the top.
3) put the cursor on line 2
4) open the colour picker (again background or font colour doesn't matter)
5) pick a colour. notice how the colour picker is still open
6) Click somewhere else in the email body to close the colour picker. 
7) Notice how no background colour is applied? Sometimes also the colour is applied to the location of the click in step 6 rather than the location in step 2. 

**Expected behavior**
Well a normal editor colour picker behaviour is expected. When text is selected selecting the colour picker does not remove selection and colour is applied. Colour picker should have a list of usual colours to pick from without having use the wheel. 
For an example of behaviour see Summer Note for instance. https://summernote.org/

**Screenshots**

**Please complete the following information:**
- Browser: windows 11 google chrome Version 114.0.5735.135 (Official Build) (64-bit)
- IMAP daemon: [e.g. courier, dovecot] not relevant
- PHP version: PHP 8.1
- SnappyMail Version: Latest as of when this is reported on nextcloud.
- Mode: Nextcloud

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Place them here (few lines) or as attachments (many lines)

**Additional context**
![image](https://github.com/the-djmaze/snappymail/assets/116327393/95a96c08-e825-40dc-b70d-72430c23a5c7)

**Comment by the-djmaze** [comment]
Go to https://snappymail.eu/demo/
When it works, then the problem is Nextcloud itself.
When it does not work, we need more people with `windows 11 google chrome Version 114.0.5735.135 (Official Build) (64-bit)` to confirm the problem is there

**Comment by the-djmaze** [comment]
I can't reproduce your problem with `109.0.5414.119 (openSUSE Build) stable (64-bits)`

When I tested with `114.0.5735.198 (openSUSE Build, ungoogled-chromium) stable (64-bits)` the problem is there.
However, when you hit the `Enter` key on your keyboard, the color is set.
This indicates the problem is the browser internal color picker and we can't fix that.

**Comment by SergeyMosin** [comment]
This issue can be reproduced in **Signature** editor (but not in the message composer) on the demo server and also applies to "Font Selector" and "Font Size Selector"

1. Go to Identity settings
2. Switch the editor into HTML mode
3. Enter some text
4. Highlight/select a portion of the text
5. Click on either "Font Selector", "Font Size Selector" or one of the color pickers
6. :boom: the selection is lost and the changes will not apply
7. To repeat: go back and EDIT the text and then proceed to Step 4

My best guess, this is happening because of the way `new Editor()` is constructed.

The "Message Composer" editor is constructed here: https://github.com/the-djmaze/snappymail/blob/99d68bc35479af37aea9548555a4adb809e58f3b/dev/View/Popup/Compose.js#L688-L693 and has `null` passed as the second parameter(onBlur)

The signature editor is constructed here: https://github.com/the-djmaze/snappymail/blob/99d68bc35479af37aea9548555a4adb809e58f3b/dev/External/User/ko.js#L92 and has a function passed as the `onBlur` param. The function resolves to here: https://github.com/the-djmaze/snappymail/blob/99d68bc35479af37aea9548555a4adb809e58f3b/dev/Common/Html.js#L842-L844 I am not entirely sure why but it looks like the `this.getData()` call somehow cause the selection loss.

In any case if the second param is set to `null` everything works as expected:
```javascript
	editor = new HtmlEditor(element, null, fOnReady, fUpdateKoValue);
```

**Comment by tregmos** [comment]
I got the same issue on standalone (non-nextcloud) version of snappymail. Both with Opera and Edge Browser on Windows 11.

**Comment by the-djmaze** [comment]
https://support.telosalliance.com/article/h4kvjxxery-getting-your-old-color-picker-back-in-google-chrome

**Comment by tregmos** [comment]
I got the latest Chrome and Opera browser on Windows, but it doesn´t work.
The point "Web Platform Controls updated UI" doesn´t exist.
There´s "Experimental Web platform features" instead, but making changes here doesn´t change anything in regard to this issue.
I also got the latest version of firefox. With firefox the surface is different. It´s like in rainloop and works fine.
So you´re right that the problem depends on the internet browser.

**Comment by jmrapin81** [comment]
I appreciate it does not happen in every browsers but it *is* happening in Chrome and it’s not some obscure browser no one uses. 
In my first post, I pointed out there are software out there that manage to have a perfectly good working color picker that works cross browser. 
Why not here ?

**Comment by the-djmaze** [comment]
I've changed the color picker to use default options.
This is a workaround for the broken Chrome color picker UI.

![afbeelding](https://github.com/the-djmaze/snappymail/assets/3752035/6997e497-17e1-4d22-861f-34be6eee6eb8)

The colors are from color blind palette "Tableau 10", developed by Maureen Stone.
