### ISSUE TITLE
Empty lines in compose mail window

### ISSUE THREAD

**Issue by phsc84** [the-djmaze/snappymail#12]
**RainLoop version, browser, OS:**
the-djmaze8, Chrome 85.0.4183.102 (64-bit), Windows 10

**Expected behavior and actual behavior:**
When starting to write a new mail, the cursor should be in the 1st line. Now there are 2 empty lines first and the cursor is in the 3rd line.

**Steps to reproduce the problem:**
see description above

**Logs or screenshots:**
![compose_mail_empty_line](https://user-images.githubusercontent.com/2138442/94059260-77a59d00-fde2-11ea-8e00-6e747c4b1824.jpg)

**Comment by the-djmaze** [comment]
This seems to be because of signatures.
The Squire editor uses `<div><br/></div>`, while CKEditor uses `<p>`.
This always results in a signature that is not empty.
The compose window first inserts '' which squire makes it `<div><br/></div>`
Then the compose window inserts the signature which results in `<div><br/></div><div><br/></div>`

Will test if Firefox and Chrome work without the `<div><br/></div>` these days.

**Comment by the-djmaze** [comment]
I've found a solution but can't solve it!
When i remove the BR from the empty DIV i can focus it now, but MUA (mail clients) don't render an empty DIV so that line is not empty (like with P).
So we must keep the BR in empty block elements (like DIV, P, BLOCKQUOTE, etc.) to keep MUA rendering a blank line.

Instead we could strip DIV+BR from the beginning and the end and see if that reduces the amount of blank lines.

**Comment by phsc84** [comment]
Thank you for your investigation. As this is only a cosmetic issue, it has low priority for sure.
But I'm happy to test again, as soon as you have a new package (e.g. djmaze9).

**Comment by phsc84** [comment]
This is still the same for SnappyMail 2.0.0-rc1. But for me this is really only a minor cosmetic flaw.

**Comment by phsc84** [comment]
It is better in SnappyMail 2.0.0-rc2. Only one empty line is shown now. From my point, this is fine now.
