### ISSUE TITLE
Snooze?

### ISSUE THREAD

**Issue by BiglifeMatt** [the-djmaze/snappymail#1221]
I know that SnappyMail will not do the scheduled mail, I believe due to security restraints, but is there a way to Snooze mail that has already come into the Inbox so it will pop up at another time at the top of the Inbox?

**Comment by randolf** [comment]
Does your SMTP server even support scheduled mail?  I've not seen support for this, and I wouldn't want it anyway because a spammer who gains unauthorized access to an account could abuse it by scheduling their spam to be delivered at later dates that could make the site's security problems appear incorrectly to end-users as unresolved.

**Comment by BiglifeMatt** [comment]
I haven't tested it on the SMTP server.  But I'm not trying to specifically handle the scheduling.  I'm looking for the Snooze-type feature.  So the email has hit my inbox but my client can snooze the message, so tell it to pop in at the top of my Inbox at a scheduled time.  I am not certain if this requires the same process as a scheduled SMTP send.  That is what I am inquiring.

**Comment by the-djmaze** [comment]
MIME has several date fields where the most important are:
- `Date`: Specifies the date and time at which the creator of the message indicated that the message was complete and ready to enter the mail delivery system.
- `Delivery-Date`: The time when a message was delivered to its recipient.

But mostly we use the IMAP INTERNALDATE. This is the internal date and time of the message on the server. It is a date and time which reflects when the message was received. 
- Messages delivered via SMTP, this SHOULD be the date and time of final delivery of the message as defined by SMTP. 
- Messages delivered by the IMAP4rev1 COPY command, this SHOULD be the internal date and time of the source message. 
- Messages delivered by the IMAP4rev1 APPEND command, this SHOULD be the date and time as specified in the APPEND command description.
https://datatracker.ietf.org/doc/html/rfc3501#section-2.3.3

So the best way is to modify the SMTP server to delay delivery so that the final delivery is postponed.

**Comment by BiglifeMatt** [comment]
I'm sorry but I might not have been very clear in what I was hoping for here.  What I am talking about is the feature in other webmail inboxes, like GMail, where I can select an email in my inbox, click the snooze button, then tell it to show up at 8am the next morning in my Inbox.  I'm not sure if that is exactly the scenario you are addressing as well here.  Perhaps it is and I just misunderstood you.  But I just wanted to re-phrase this in case I wasn't clear the first time.  Thanks.

**Comment by the-djmaze** [comment]
This is not fully possible.

You could misuse the `APPEND` command and specify date and time in the future.
But SnappyMail does not filter on date before "now".

However, you could make a plugin to achieve this.
1. Fetch message
2. Delete message
3. APPEND message with your "snooze" date and time
4. Set application.ini `message_list_permanent_filter` to `BEFORE CURRENTDATE`

You only need to figure out how to make CURRENTDATE dynamic

**Comment by BiglifeMatt** [comment]
ok. this makes sense.  thank you!
