### ISSUE TITLE
2FA enabled and enforced can be bypass by entering 2 times no or false TOTP

### ISSUE THREAD

**Issue by Nono-m0le** [the-djmaze/snappymail#1241]
**Describe the bug**
When 2FA plugins is enabled and enforced, TOTP Code setup succesfully for an user, trying to connect to this user (with good username and password) but *without* or *false* TOTP Code, succeed after the 2nd try (aka, pressing 2 times "connect") 

**To Reproduce**
1. Go to the ?admin page and install the Extension "two-factor-auth"
2. enforce the 2FA, on the settings of the extensions
3. connect to an user and setup the TOTP CODE
4. LOGOUT from the user 
5. enter only username and password (leaving the TOTP filed empty
6. press 2 times on "connect"
7. your a login...

**Expected behavior**

Connection shouldn't be possible without (correct) TOTP code

**Please complete the following information:**
- Browse: Firefox 117 (android / Linux)
- IMAP daemon: dovecot
- PHP version: 8
- SnappyMail Version: latest 2.28.4
- Mode: standalone

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Place them here (few lines) or as attachments (many lines)

**Additional context**

**Comment by tinola** [comment]
I can confirm this bug. Same here.

**Comment by MI-KY** [comment]
@the-djmaze  I'm not sure, but could this problem arise because the function `DoLogin` is launched at the hook `login.success` and not at some point like `login.credentials`? https://github.com/the-djmaze/snappymail/blob/c60f8776f437abb254e3119ca8be99fc6261ebd3/plugins/two-factor-auth/index.php#L23
https://github.com/the-djmaze/snappymail/blob/f6ef6d45ff012a005c6ed19ea201ccc8bdf6568d/snappymail/v/0.0.0/app/libraries/RainLoop/Actions/User.php#L52

**Comment by the-djmaze** [comment]
Yes, that could be it. Will look into it

**Comment by Nono-m0le** [comment]
@the-djmaze I'm sorry but I just got the opportunity to upgrade to 2.29.1 and the issue remains exactly the same.
Could you please re-open the ticket and/or let me know how to fix the (same) issue described on the original ticket ?
