### ISSUE TITLE
Please prioritize dockerization!

### ISSUE THREAD

**Issue by Leopere** [the-djmaze/snappymail#1244]
Can you please put more of priority into containerizing your work I desperately want to rely on Snappymail this PR works excellent for me https://github.com/the-djmaze/snappymail/pull/965 Please take the time to put this at the front <3

**Comment by mschilli87** [comment]
What stops you from using the code from that PR in your own fork and maintaining it until it reaches the top the list? IMHO there are more important issues to address first but I would not even think of telling somebody who puts in all this work for me for free (likely even in their unpaid spare time) what to do when.

**Comment by Leopere** [comment]
> What stops you from using the code from that PR in your own fork and maintaining it until it reaches the top the list? IMHO there are more important issues to address first but I would not even think of telling somebody who puts in all this work for me for free (likely even in their unpaid spare time) what to do when.

Do you have a difficult time understanding that users as well as coders are capable of having a github account?

**Comment by mschilli87** [comment]
@Leopere:

I didn't take anything personally. I just got a notification about an 'issue' with a software I rely on that I subscribed to because I want to know about potential securoty issues as soon as possible and saw that while the community is investigating one such crucial flaw in this software, somebody else came by and 'asked' (with an exclamation sign!) to prioritize a feature that i) I (personally!) consider irrelevant, ii) apparently already has a working patch in a PR, and iii) did not receive any additional useful information other than 'me too' from a random user (or 'coder' if you prefer). Your post added nothing a :+1: to the PR you linked wouldn't have achieved as well, besides sending out email notifications to people like me that follow this repo for other reasons and have actively unsubscribed from that PR they don't care about. To me this screams 'me, me, me, hear, look at me, I am more important than whatever you are working on right now' and I don't like the attitude. But since I am not actively involved in the development of snappymail, I do no see how this affects me at all besides some additional spam in my inbox. So I did not take any offense and I sincerly apologize if I hurt your feelings with my comment. I had good intentions and tried to suggest a solution for you that might advantageuos to the community (incl. me, yes) in my (very humble) opinion. Feel free to hide my comments as off-topic.

I thought I did understand how FOSS works but I might be wrong: If there is a working PR, you *can* use the software. I *do* use it without this feature. And I don't see how having an additional user that cannot  (as per their own words) use software without docker and does not add anything to the discussion but spam  would be benefitial for the project. Note that I think the same is true for me: I am leaving the second comment here that does no advance the project in any way. So while I might develop code myself and actively contribute elsewhere, for this repo I am just a user. And if I was active in this repo, the kind of user I am right now would annoy me. Just slighly but enough not to long for more of them. 😉

So I'll leave it wishing you a nice day and that you'll find a way to use snappymail, that the PR will get the prioroty you need soon and I apologize to you and anyone else for any harm I might have caused with my comments, which I am going to hide to save posterity some time. 😉

**Comment by Leopere** [comment]
@mschilli87, thanks for the thoughtful reply. I'm so used to gatekeeper neckbeards on GitHub policing things as if everyone who ever interacts with a Git issues page should be expected to be entirely omniscient for whatever reason the PR intends to become mainline as a method for the app to be increased more easily, typically so long as you don't break userspace for an application the docker stuff usually doesn't require much maintenance if done correctly. It almost always increases the stability and security of a container and production system to have something the original developer scopes, not necessarily the community.  

Ideally, you want to accommodate one singular configuration rather than every way a misguided individual could muddle their configuration locally. This would typically reduce potential support issues and keep the original dev focused more peacefully on the task they came here to solve. I hoped to provide an issue that people could follow and possibly engage with to garner support for a feature as you commonly do on a git issues page.

**Comment by Leopere** [comment]
Could it be? Could I love you any more for having made snappy?!
