### ISSUE TITLE
Emails inconsistently auto-tagged as Important

### ISSUE THREAD

**Issue by KenBW2** [the-djmaze/snappymail#1252]
**Describe the bug**
Whenever I load my inbox I end up with around 50% of the emails in red, tagged as Important

**Expected behavior**
None of the emails are tagged without my intervention

**Screenshots**
![Screenshot from 2023-09-21 19-36-42](https://github.com/the-djmaze/snappymail/assets/366540/ebbbd37a-5c65-4be5-b0a6-427a1b509474)

**Please complete the following information:**
- Browser: Any
- IMAP daemon: 
- PHP version:8.1.23
- SnappyMail Version:2.28.4
- Mode: Nextcloud

**Comment by the-djmaze** [comment]
Remove Nextcloud Mail app. It does that, not SnappyMail

**Comment by KenBW2** [comment]
I don't have the Nextcloud mail app installed

**Comment by the-djmaze** [comment]
> I don't have the Nextcloud mail app installed

Are you sure? As that was the issue at #881

**Comment by KenBW2** [comment]
Hm, that makes me wonder. I have a couple of old NC instances lying around. I wonder if I've set those up with Mail. I'll investigate and report back either way

**Comment by KenBW2** [comment]
@the-djmaze Can I have this issue reopened? It's months later, and I have no other NC instances, nor do I have the mail app enabled on my only active NC instance and am still getting the issue

![Screenshot from 2023-11-08 01-23-05](https://github.com/the-djmaze/snappymail/assets/366540/aee5b8a1-7f32-49ac-bdb3-da8ea3007bc8)

**Comment by the-djmaze** [comment]
@KenBW2 i could reopen the issue, but it is not SnappyMail that causes it.
You should investigate which application is doing this.

**Comment by scubamuc** [comment]
@the-djmaze, thanks for this.

My IMAP mails were being tagged without my request too.

Turns out that one Nextcloud instances had "Nextcloud Mail app" enabled and was happily autotagging my IMAP mails. Sadly the  Nextcloud Mail folks make autotagging a default setting. 

To solve unwanted tagging of Mails, check whether there is another client (e.g. Thunderbird with autotagging, Nextcloud Mail with autotagging) accessing your IMAP mails. Remove autotagging option from these clients.

Yet another reason for using Snappymail... great software, great team ✔

**Comment by Luncheon3462** [comment]
@scubamuc where did you find the setting in nextcloud mail to turn off auto logging.

**Comment by the-djmaze** [comment]
![afbeelding](https://github.com/the-djmaze/snappymail/assets/3752035/cf292514-9d61-405b-b106-ef3d1e52fab0)

**Comment by scubamuc** [comment]
dank u wel... thanks,

@Luncheon3462 I took the easy path and simply removed the mail app in Nextcloud. As far as I can tell, that is the only client automatically tagging mails.
