### ISSUE TITLE
search does not search in a second mail account

### ISSUE THREAD

**Issue by ferdiga** [the-djmaze/snappymail#1261]
**Describe the bug**
The search returns only results from "files" and the first account from "snappy mail".
IMO Nextcloud unfiied search should  search  in ALL accounts of the user.

**To Reproduce**
1. Go to 'snappymail'
2. Create a second account and send some distinctive different mails with at least one identical word to the 2 accounts
3. both mails should (and do so in my case) show up in the very mail account
4. Search for the "word" - only one mail (in the main account?) will be found

**Expected behavior**
all mail accounts should be searched .

**Screenshots**

**Please complete the following information:**
- Opera / Brave / 
- IMAP daemon: [e.g. courier, dovecot]
- PHP version: 8.2
- SnappyMail Version: 2.28.4
- Mode: nextcloud

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Place them here (few lines) or as attachments (many lines)

**Additional context**

**Comment by the-djmaze** [comment]
SnappyMail only searches in the current active mail account.
There is no way SnappyMail can search in multiple nor have a merged/single view for all.

**Comment by ferdiga** [comment]
Hi,
"There is no way SnappyMail can search in multiple nor have a merged/single view for all."

Does it mean it is impossible or just not coded?

**Comment by the-djmaze** [comment]
Not coded and for many reasons not.

A single IMAP connection with search could take several seconds.
What would happen if you multiply that?
Will you use Nextcloud Search when it takes 1 minute to search?
I so, then still the SnappyMail interface can't show it unless it is reloaded through an account switch.

All that because SnappyMail does not store mail locally.
It is not like Thunderbird, Nextcloud Mail nor RoundCube

**Comment by ferdiga** [comment]
thanks for explaining.
