### ISSUE TITLE
Checking all folders

### ISSUE THREAD

**Issue by VlaK0r** [the-djmaze/snappymail#1372]
Hello!
Thank you for your hard work!

Checking for new emails takes place only in the "Inbox". But I have other manually created folders where incoming messages are moved according to the rules. For some reason, automatic verification does not occur in them.
Please tell me how to fix it?

**Comment by the-djmaze** [comment]
Your question has been asked before.
Why this is not implememted has to do with one important reason that has to be solved.
When you move emails to a folder (say archive, trash or spam) it would also notify you, because "new" mail has arrived in those folders.

For example: move unread mail to inbox, it should notify you (which is weird).

**Comment by VlaK0r** [comment]
> Your question has been asked before. Why this is not implememted has to do with one important reason that has to be solved. When you move emails to a folder (say archive, trash or spam) it would also notify you, because "new" mail has arrived in those folders.
> 
> For example: move unread mail to inbox, it should notify you (which is weird).

Everything is clear. I hadn't really thought about it. Thanks!
