### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'formattedName') [Google Chrome only]

### ISSUE THREAD

**Issue by fs1** [the-djmaze/snappymail#1382]
**Describe the bug**
Clicking on the reply button (or 'reply all' or 'forward') triggers no 'pop-up' of the message. Instead the following message appears in the console:
> Uncaught TypeError: Cannot read properties of undefined (reading 'formattedName')
>     at new ComposePopupView (app.min.js:1:122877)
>     at ps (app.min.js:1:44612)
>     at ys (app.min.js:1:46373)
>     at AppUser.showMessageComposer (app.min.js:1:185920)
>     at Ni (app.min.js:1:79076)
>     at MailMessageView.replyOrforward (app.min.js:1:160543)
>     at app.min.js:1:157053
>     at MailMessageView.s [as editAsNewCommand] (app.min.js:1:156996)
>     at HTMLAnchorElement.<anonymous> (libs.min.js:1:34674)
> ComposePopupView @ app.min.js:1
> ps @ app.min.js:1
> ys @ app.min.js:1
> showMessageComposer @ app.min.js:1
> Ni @ app.min.js:1
> replyOrforward @ app.min.js:1
> (anonymous) @ app.min.js:1
> s @ app.min.js:1
> (anonymous) @ libs.min.js:1

**To Reproduce**
0. Open Google Chrome (in version 120.0.6099.130 or 120.0.6099.200)
2. Go to 'Inbox'
3. Click on 'any mail'
4. Click on the reply icon (or on the menu icon and choose "reply all" or "forward"
5. nothing happens (except a browser console message)

**Expected behavior**
A pop up of the selected message should appear, ready to answer or forward the message.

**Please complete the following information:**
- Browser: Chrome 120.0.6099.200
- IMAP daemon: dovecot
- PHP version:

> PHP 8.2.7 (cli) (built: Jun  9 2023 19:37:27) (NTS)
> Copyright (c) The PHP Group
> Zend Engine v4.2.7, Copyright (c) Zend Technologies
>     with Zend OPcache v8.2.7, Copyright (c), by Zend Technologies

- SnappyMail Version:

> $ dpkg -s snappymail
> Package: snappymail
> Status: install ok installed
> Maintainer: SnappyMail <debian@snappymail.eu>
> Architecture: all
> Version: 2.32.0

- Mode: standalone

**Additional context**
Using Firefox or Edge the pop-up appears. So maybe this is a Google Chrome bug (I am too little familiar with JS to judge)?

**Comment by the-djmaze** [comment]
What does your `/#/settings/accounts` (Settings -> Accounts) page say?

It is strange that your IdentityUserStore is empty.

**Comment by fs1** [comment]
Well - I am sorry, but I can't reproduce this error. In the meantime it works again.

**Comment by GustavoSatig** [comment]
I am also experiencing the same issue.

Steps to reproduce:
1. Open the Contacts screen.
2. Select a contact.
3. Press F12 and click the option to send an email.

Expected behavior:
- The email composition window should open.

Actual behavior:
- The Email screen appears, but the composition window does not open.
- An error is logged in the console.

**Important note:**  
This issue does not occur consistently. Sometimes the email composition window opens as expected, and other times it does not.

**Console error:**

```
Uncaught TypeError: Cannot read properties of undefined (reading 'formattedName')
    at new ComposePopupView (app.min.js?v=4.18.2:1:142079)
    at Ms (app.min.js?v=4.18.2:1:49669)
    at Ns (app.min.js?v=4.18.2:1:51468)
    at AppUser.showMessageComposer (app.min.js?v=4.18.2:1:213383)
    at Er (app.min.js?v=4.18.2:1:109306)
    at wr (app.min.js?v=4.18.2:1:109169)
    ...
```

**Additional details:**
- SnappyMail version: 2.38.2
- PHP version: 8.3

After analyzing the issue, it seems that the `loadAccountsAndIdentities` function is not asynchronous, which causes the code flow to continue before the store is properly updated with the identities. 

I tried some alternatives using Promises but was not successful. However, this seems to be the root cause of the problem.
