### ISSUE TITLE
Message header parsing issue

### ISSUE THREAD

**Issue by sm-boogie** [the-djmaze/snappymail#1403]
I have emails here where the From: or To: headers are in the following format:

```
From: =?iso-8859-1?Q?L=F6stname=2C_Firstname_-_COMPANY?=
 	<F.Loestname@company.com>
```

In the message view, these are parsed as:

To: Löstname, "Firstname - COMPANY" <F.Loestname@company.com>

Note the incorrect position of the first "

I'm not sure whether the umlauts are the problem here.
When replying to such a message, SnappyMail uses only the part inside the quotes as the name of the recipient, i.e. "Firstname - COMPANY".

SnappyMail 2.33.0
Nextcloud 28.0.2 RC1
PHP 8.2.7

**Comment by the-djmaze** [comment]
https://datatracker.ietf.org/doc/html/rfc2822#section-3.4

Address-list entries are separated by comma `,`.
So you could have: `From: user1@company.com, user2@company.com`

In your case it is `name-addr = [display-name] angle-addr`
`display-name` is equal to `phrase`.

https://datatracker.ietf.org/doc/html/rfc2822#section-3.2.6 says:
```
phrase          =       1*word / obs-phrase
word            =       atom / quoted-string
```

`atom` is described at https://datatracker.ietf.org/doc/html/rfc2822#section-3.2.4
`quoted-string` is described at https://datatracker.ietf.org/doc/html/rfc2822#section-3.2.5

In your case it is a valid atom string.

The problem occurs after the decoding of the Q string.
Because then the `=2C` becomes a comma and it is detected as address-list.
So that will be:
```
[0] = Löstname
[1] = Firstname - COMPANY <F.Loestname@company.com>
```

So it looks like SnappyMail is not at fault, it is the remote mailer.
Because headers are decoded first, then processed.
If i'm wrong, please provide the right documentation where it says so.

**Comment by sm-boogie** [comment]
Oh wow, thank you!

**Comment by sm-boogie** [comment]
I can confirm that names look fine now.

**Comment by the-djmaze** [comment]
Great!

The problem was inside MailSo.
So RainLoop and Afterlogic still have this issue.
