### ISSUE TITLE
SnappyMail Nextcloud 2.35.4 S/Mime Signature gone

### ISSUE THREAD

**Issue by martintm86** [the-djmaze/snappymail#1505]
Since the last Update today to 2.35.4 in my Nextcloud the S/Mime Signature feauture have an issue. The button is gone.
I have deleted the data directory and reconfigured my Account with s/mime. But the problem still exists.
Please Fix. If you need more information or if i can Test anything for you please contact me...
Encryption is ok. But without s/Mime signature too...

![Bildschirmfoto 2024-03-18 um 13 36 19](https://github.com/the-djmaze/snappymail/assets/75777460/b8a64aec-1970-4688-aa21-cb0cd3cf7c34)

![Bildschirmfoto 2024-03-18 um 13 40 04](https://github.com/the-djmaze/snappymail/assets/75777460/bde429e3-3460-4984-a282-294623719d86)

**Comment by the-djmaze** [comment]
Your private key is marked in red.
Is it incomplete?

**Comment by the-djmaze** [comment]
Your private key is marked in red.
The problem is `RSA` on the first line as SnappyMail only accepts ENCRYPTED or none-password protected.
https://github.com/the-djmaze/snappymail/blob/190db75c191bbed33356ca36944aadc4c7cd0be7/dev/Model/Identity.js#L36

Remove RSA, maybe it works for your password-less private key (you should set a password for protection).

**Comment by martintm86** [comment]
Ok Thank you! Now in pkcs8 anything is ok. A little Error Message will be perfect here...
;-)

**Comment by the-djmaze** [comment]
> A little Error Message will be perfect here...

Well, i just added a "change passphrase" interface for easy converting the insecure RSA keys :smile:
