### ISSUE TITLE
JMAP support

### ISSUE THREAD

**Issue by jkaberg** [the-djmaze/snappymail#1550]
**Is your feature request related to a problem? Please describe.**
I'm considering self-hosting mail for privacy - and I'm considering the [Stalwart mail server](https://github.com/stalwartlabs/mail-server) for this purpose with snappymail as an frontend. However seeing as the [IETF is pushing for JMAP](https://www.ietf.org/blog/jmap/) I was wondering if this is something you've considered? (yes I know - Stalwart supports IMAP/SMTP)

**Describe the solution you'd like**
Implement support for the [JMAP specification](https://jmap.io/)

**Comment by the-djmaze** [comment]
JMAP is partially implemented.
I've noticed that JMAP is lacking many features that SnappyMail is using.
Therefore JMAP is still not considered als drop-in alternative and is therefore not supported.

**Comment by marclaporte** [comment]
> I've noticed that JMAP is lacking many features that SnappyMail is using.

Can you please share a few examples?

JMAP is an open standard. We can all work together to make it better.

Thanks!

**Comment by mdecimus** [comment]
> JMAP is partially implemented.

This is incorrect, JMAP is a published IETF standard.

> I've noticed that JMAP is lacking many features that SnappyMail is using.

Also incorrect, in fact JMAP offers more capabilities and is more flexible that IMAPrev2. It also supports E-mail Submissions, replacing SMTP for client email submissions.

**Comment by the-djmaze** [comment]
Where does JMAP define sorting and threading?
Where does JMAP define quota handling?
Where does JMAP define correct handling of all ACL features?
Where does JMAP define handling of virtual and alias mailboxes?
And there are many more...

**Comment by the-djmaze** [comment]
> > Where does JMAP define sorting
> 
> Here: [RFC8621 - Section 4.4.2](https://datatracker.ietf.org/doc/html/rfc8621#autoid-41)

`The following values for the "property" field on the Comparator object SHOULD be supported for sorting`

So how do we know if they are supported?
Is there a capabilities system?

> IMAP does not define handling of virtual and alias mailboxes either. Some servers support virtual/alias mailboxes through the `METADATA` extension but this is not standard.

IMAP has 3 types of namespaces:
1. Personal Namespace(s)
2. Other Users' Namespace(s)
3. Shared Namespace(s)

SnappyMail handles them and the demo has:
```json
{
	"namespaces": {
		"@Object": "Object/Namespaces",
		"personal": [
			{
				"prefix": "",
				"delimiter": ".",
			},
			{
				"prefix": "virtual.",
				"delimiter": ".",
			}
		],
		"users": [
			{
				"prefix": "shared/",
				"delimiter": "/",
			}
		],
		"shared": []
	}
}
```
`virtual.` is a non-existing mailbox and `virtual.All` exists.

> stating that JMAP is only partially implemented or incomplete is inaccurate.

Take a look here:
https://github.com/the-djmaze/snappymail/blob/332f9a79e387965be41a69f06e361953f048e143/snappymail/v/0.0.0/app/libraries/MailSo/Imap/Folder.php#L149-L180

There you can see only a few parts are JMAP.
JMAP does not understand ACL properly, nor does it support `delimiter`, `attributes` `metadata`.
I'm not here to argue what is there and what not.
JMAP will just not happen until JMAP servers can tell what they support and what not (like IMAP CAPABILITY)

**Comment by mdecimus** [comment]
> `The following values for the "property" field on the Comparator object SHOULD be supported for sorting`
> 
> So how do we know if they are supported? Is there a capabilities system?

Yes, the [JMAP Session Resource](https://datatracker.ietf.org/doc/html/rfc8620#autoid-13) lists the servers capabilities as well as other information.

> IMAP has 3 types of namespaces:

IMAP namespaces are mapped to regular JMAP folders in most JMAP servers. In any case, namespaces are not needed to have a functional mail client. For example, Gmail, the most widely used webmail client, does not use namespaces and users don't even notice it.

> There you can see only a few parts are JMAP. JMAP does not understand ACL properly, 

The ACL property is an IMAP thing, JMAP uses the Sharing extension linked in a previous comment.

> nor does it support `delimiter`, `attributes` `metadata`.

They are not supported because those are IMAP specific mechanisms that JMAP does not need. And, most importantly, it is perfectly possible to have a fully functional mail client without those extensions.

> I'm not here to argue what is there and what not. JMAP will just not happen until JMAP servers can tell what they support and what not (like IMAP CAPABILITY)

As mentioned above, they do [support listing capabilities](https://datatracker.ietf.org/doc/html/rfc8620#autoid-13).

In any case, I am not trying to convince you to implement JMAP, it's your product after all. What I just wanted to point out is that JMAP is a mature protocol and it is incorrect to say that it can't be implemented because it lacks features.

If you have some time, I suggest that you read the JMAP Core, JMAP Mail, JMAP Quotas and JMAP for Sieve Scripts specifications.
