### ISSUE TITLE
Add an occ command to set up the 

### ISSUE THREAD

**Issue by mmallejac** [the-djmaze/snappymail#1552]
For automation purpose, it would be super great to be able to add primary email and password with an `occ` command, something like:

`occ snappymail:add USER email password`

Probably this requires some further thinking that we can discuss if you're open to the idea !

**Comment by the-djmaze** [comment]
You mean in the user additional settings?

**Comment by mmallejac** [comment]
Yes, this where we set up the mail and password, for each user. Most of them do not know their own main mail password, since we - their IT service - create their email address and set its password.

Not sure in which sub-part of `occ` that could be done, whether inside `occ user:setting` or maybe by creating its own subset, like `occ snappymail:action user arg value`  

For instance onlyoffice:
`occ onlyoffice onlyoffice:documentserver` without args returns the current server and with some other arguments can completely configure the way onlyoffice is installed.

**Comment by the-djmaze** [comment]
It seems you already can:

Get the current settings
`sudo -u nextcloud php occ user:setting userid snappymail`

Set login username
`sudo -u nextcloud php occ user:setting userid snappymail snappymail-email "my@example.tld"`

Set login passphrase
`sudo -u nextcloud php occ user:setting userid snappymail passphrase "c29kaXVt.3oxYdxP0FF.dGhpc2lzbXlwYXNzd29yZA"`

The problem here is the passphrase encryption.

So the above commit should work (i did not test it).

**Comment by mmallejac** [comment]
Great ! Many thanks 

_The problem here is the passphrase encryption_ 

So with this command, is the passphrase encrypted or clear ?
And if encrypted, how can we crypt the clear to pass it to this command ?

**Comment by the-djmaze** [comment]
The above commit adds the special snappymail command that will properly encrypt a plain password.
Although i don't like the idea because every shell command you use, will put the passphrase in the `.bash_history`.

That's why the imapsync.php i've created asks for them on the prompt (no idea if Nextcloud can).
https://github.com/the-djmaze/snappymail/blob/372e4bc1c00d123cd3ce903a3a0816ce6ba96bf3/snappymail/v/0.0.0/imapsync.php#L102-L115

**Comment by the-djmaze** [comment]
Ok i've added the prompt to type passphrase and it works.

Now you can do this so that it doesn't log the passphrase in the `.bash_history`
```
[root@nextcloud]# sudo -u nextcloud php occ snappymail:settings djmaze my@example.tld
The current PHP memory limit is below the recommended value of 512MB.
password: test
```

**Comment by mmallejac** [comment]
Great ! 
Actually, the `occ` command for user password works the same way :
`occ user:resetpassword [--password-from-env] [--] <user>`

My goal is to be able to script that, and I think it is okay if used along with a tool like `expect`.

I'll to some testing, thanks again !
