### ISSUE TITLE
Resource: Provide option to use the CKEditor plugin

### ISSUE THREAD

**Issue by fabiodepin** [the-djmaze/snappymail#1593]
The current Squire plugin is quite limited in terms of features, such as resizing and positioning images, use of tables, among other features.
Points that CKEditor would resolve.

Including resolving image redirection when creating an email signature.

Current
![Screenshot from 2024-05-23 16-00-51](https://github.com/the-djmaze/snappymail/assets/1088516/846d0fc4-919f-49d6-8080-b4e338664272)

Proposed:
![Screenshot from 2024-05-23 15-59-43](https://github.com/the-djmaze/snappymail/assets/1088516/b91c81b4-385f-4641-9573-c9a8ae7a96bc)

**Comment by the-djmaze** [comment]
Browsers behave differently on the `<img>` tag.
The most annoying being Chrome that does not focus/select the image.

That's why many editors have a workaround with lots of code to get this going.

Since SnappyMail is also mobile friendly, all those "workaround" editors are not working properly.

But if you get CKEditor working in SnappyMail, feel free to provide it as extension.
