### ISSUE TITLE
Improve the contact search component when writing an email

### ISSUE THREAD

**Issue by fabiodepin** [the-djmaze/snappymail#1595]
Currently there are some problems with using the datalist, such as the use of arrows and enter.
For those using a MacBook, there are more problems.

One suggestion is to change the component to the image below.

From:
![Screenshot from 2024-05-24 14-40-18](https://github.com/the-djmaze/snappymail/assets/1088516/dac0e083-a4f9-4e27-9d8c-5481aad20b22)

To:
![Screenshot from 2024-05-24 14-35-27](https://github.com/the-djmaze/snappymail/assets/1088516/aadbcce4-ec05-4992-9551-fe4350666a4c)

Thanks

**Comment by the-djmaze** [comment]
As you can read in the closed issues, SnappyMail is bound to the behavior of the browser.

If we develop our own custom datalist component we need to do a lot of work as there are many ways to respond to user events (mouse, keyboard, touch, pen, etc.).
Currently i don't see any real benefits to extend the code size (javascript + css + html + aria) other then "it makes the UI beautiful".
Because currently "it works" in any browser.

**Comment by the-djmaze** [comment]
But you can try and play around with https://codepen.io/iamsidd_j/pen/qBRWNQQ

**Comment by fabiodepin** [comment]
Hello,

I also have this improvement ready.
I send PR as soon as I have time during the week, along with those other tasks.

Thanks

**Comment by gymbrall** [comment]
> But you can try and play around with https://codepen.io/iamsidd_j/pen/qBRWNQQ

```
else if(e.keyCode == 13){
    e.preventDefault();
        if (currentFocus > -1) {
          /*and simulate a click on the "active" item:*/
          if (browsers.options) browsers.options[currentFocus].click();
        }
       else //currentFocus is -1, so if enter is pressed, choose the first item
         {
           if (browsers.options) browsers.options[0].click();
         }
  }
```
