### ISSUE TITLE
Read mail - "Display external images" does not work

### ISSUE THREAD

**Issue by phsc84** [the-djmaze/snappymail#16]
**RainLoop version, browser, OS:**
2.0.0-rc1, Chrome 85.0.4183.102 (64-bit), Windows 10

**Expected behavior and actual behavior:**
In HTML mails, images are not displayed by default (which is perfectly ok). But there is a status bar, where you can click on to display external images.
![screenshot_display-external-images](https://user-images.githubusercontent.com/2138442/94359453-9a1c0c80-00a7-11eb-8b99-3bf58aa3ca01.jpg)
When you click on this bar, the images are still not displayed.

**Steps to reproduce the problem:**
see description above

**Logs or screenshots:**
Browser log
Refused to load the image 'https://hostmecdn.azureedge.net/photos/original/bc0403c3a0f2b32a309b46b26d8e86b8' because it violates the following Content Security Policy directive: "img-src 'self' data:".

/apps/mail/#/mailbox/INBOX:1 Refused to load the image 'https://res.cloudinary.com/hostme/image/upload/v1485349543/mails/email/fb.png' because it violates the following Content Security Policy directive: "img-src 'self' data:".

/apps/mail/#/mailbox/INBOX:1 Refused to load the image 'https://res.cloudinary.com/hostme/image/upload/v1485349589/mails/email/inst.png' because it violates the following Content Security Policy directive: "img-src 'self' data:".

/apps/mail/#/mailbox/INBOX:1 Refused to load the image 'https://u2487786.ct.sendgrid.net/wf/open?upn=WBXUONgQrRkyTH6eqZGcKm4KaVKReDHEXQv5BzVFwnqWs5A5YWADXTSLDUGRnY9aYlQ3d1NN0VXATnplddYng2S4P6YBwKRnxI0LErQA90mQCkijzysrC42fzjSYokcNr4b9vEAQIXOKWFaPAK3R7LcNq4LcyOHwP08pn5mf7G6NaDA586MjuG38-2FQi5j4PISDGYQa0KunD3tBmFzHdXm7d2gwFGdWaX2zk-2B-2F6qX-2Fs4-3D' because it violates the following Content Security Policy directive: "img-src 'self' data:".

**Comment by the-djmaze** [comment]
Correct, currently the CSP is very strict to disallow everything from other domains.
This is for privacy concerns regarding tracking pixels and such (mailings).

In application.ini you can modify `content_security_policy` to allow more for the `img-src`.
Would be nice to configure per user login to allow it or not, or let the user control it through their own pihole/ublock origin/firewall/etc.
But this last one is an issue on mobile networks.

So an img blacklist system in SnappyMail itself to prevent tracking would be better, however that might become a very long list due to mailinglist systems with their remote image tricks.

Will keep this open for (a long) discussion.

**Comment by ervee** [comment]
> In HTML mails, images are not displayed by default (which is perfectly ok). But there is a status bar, where you can click on to display external images.

What happens when you enable the admin setting "Use local proxy for external images" in the Security setting?
This lets your server download the images and your browser eventually loads them from a URL the same as your webmail server. This probably plays nicer with the strict content security.

This feature was introduced in this commit for who want to investigate the inner workings of this setting:
https://github.com/RainLoop/rainloop-webmail/commit/3ae18e76c662de9a9d5f850ee11bd69156d24678

**Comment by the-djmaze** [comment]
@ervee is correct! I totally forgot about the proxy.
It does solve the CSP.
I could als change the CSP: proxy on = strict CSP, proxy off = loose CSP

But that doesn't stop mail tracking (regarding read/unread stats). So for better tuning we can still have a list for downloading yes/no.

**Comment by phsc84** [comment]
@ervee 
Thank you for the hint. This solved the problem!
@the-djmaze 
How about an FAQ in the wiki, where we can explain such settings and their effect? If you agree, I would be happy to help to setup the FAQ.

**Comment by the-djmaze** [comment]
@phsc84 somehow you seem to be missing 'https:' in the img-src.
This was added later due to the problem you describe.

I made changes so take the proxy into account.

**Comment by ervee** [comment]
> But that doesn't stop mail tracking (regarding read/unread stats). So for better tuning we can still have a list for downloading yes/no

Correct, it does not stop tracking. But if you ask me, showing the images and subjecting themselves to possible tracking is a user choice.

**Comment by phsc84** [comment]
With SnappyMail 2.0.0-rc2 this also works with "Use local proxy for external images" disabled. Some mails still don't get perfectly displayed. Will have a look at this later.

**Comment by phsc84** [comment]
With SnappyMail 2.0.0-rc2 I get the following error.
[log_display_images.txt](https://github.com/the-djmaze/snappymail/files/5373687/log_display_images.txt)

**Comment by phsc84** [comment]
The browser log shows the following messages:
Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure element '<URL>'. This request was automatically upgraded to HTTPS, For more information see <URL>
Refused to load the image '<URL>' because it violates the following Content Security Policy directive: "img-src 'self' data:".

**Comment by the-djmaze** [comment]
I already thought so. Somewhere someone still uses insecure HTTP.
Hard to make secure mail insecure.

Will allow http in the default when not using proxy.

**Comment by phsc84** [comment]
With SnappyMail 2.0.0-rc3 this works perfectly fine!
Thank you very much! It is a pleasure to work with SnappyMail!
