### ISSUE TITLE
Two authentication systems ? Nextcloud + Snappymail login

### ISSUE THREAD

**Issue by mmallejac** [the-djmaze/snappymail#1610]
Hello !

This is related to #1602 

I am under the impression that there are two authentication systems when Snappymail is used with Nextcloud.
- the first is within Nextcloud itself, since the main mail / password is set under settings / additional settings (or using `occ snappymail:settings`)
- the second is the Snappymail login page

With the login issue revealed with #1602 I have multiple cases, difficult to understand:
- within Nextcloud (under settings / additional settings) the mail address is set but the password has got lost 
- or even though the address and password are correctly set within Nextcloud, sometimes the Snappymail login page still appears

Wouldn't it be good to have only the Nextcloud authentication when Snappymail is used in conjunction with Nextcloud ?

Not sure, but I am under the impression that the Snappymail authentication page uses a client side mechanism, which goes against the flexibility: a user is ok with one of his setup (computer / browser) but not with another one.

Sorry if this is not very clear, just trying to understand what's under the hood !

**Comment by the-djmaze** [comment]
You login on IMAP server using `name` and `mypassword`.
You login on Nextcloud as `name` and `mypassword`.
Now SnappyMail can login easily.

You login on IMAP server using `name@company` and `mypassword`.
Your Nextcloud account primary email address is `name@company` and `mypassword`.
Now SnappyMail can login easily.

In any other case they are different and there's no way to match them.
So you go to Nextcloud -> User Settings -> Additional and fill in your IMAP credentials.
Now when you login in Nextcloud, under the hood SnappyMail logs in using the provided credentials.
But when that login fails it will remove the provided password.
Why? Because else the IMAP server is flooded with failed login attempts.
