### ISSUE TITLE
Strange wait cursor

### ISSUE THREAD

**Issue by bwdugan** [the-djmaze/snappymail#165]
Thank you for all this work on Snappymail!  I have switched from rainloop and it is working very well.

On my chromebook (Chrome 94) I get a strange horizontal copy of the spinning wait cursor (the one in the left-most box in the row of icons above the message list):  whenever that icon is spinning, if I move the cursor into the message view area then I get a horizontal line of the individual circle segments displayed next to each other.  I guess they should display superimposed on top of each other.  Unfortunately this is not captured by a screenshot. 

Maybe this is a know issue but I couldn't find it in a search.  Or maybe it is just an issue on my particular chromebook (i will check on other computers when I am back in the office next week).

In any case this is just a minor thing.

**Comment by bwdugan** [comment]
I am closing this issue because I see this strange behavior in unrelated browser applications.  I guess it is a browser or OS issue.  Sorry for the noise!

**Comment by the-djmaze** [comment]
The issue is this:
1. there's a background process that fetches data from server
2. a "progress" cursor is shown (when moving mouse)
3. fetch process has completed
4. "progress" cursor is still shown unless you move the mouse

I have this issue in Firefox as if Firefox is not updating the pointer unless the pointer is moved.
