### ISSUE TITLE
Multiple line breaks are not displayed

### ISSUE THREAD

**Issue by Loosen-IT** [the-djmaze/snappymail#1666]
This issue relates to the Nextcloud plugin.

Since the last update, multiple line breaks are no longer displayed for recipients. Instead, they are shown as one. Although line breaks are displayed properly in the visual editor, they are "removed" as soon as the mail is sent. If the mail is opened again after it has been sent, the line breaks are also no longer displayed.

I think it has something to do with the fact that a new div is generated with every line break.

1. Write an email
2. Divide sections with multiple linebreaks
3. Send and reopen the email

Email preview in the visual editor:
![visual_editor](https://github.com/user-attachments/assets/5206ed88-acc5-489e-8aa3-4ff42faad683)

Message actually sent:
![sent_email](https://github.com/user-attachments/assets/7ed4fe7c-cb1a-4962-802f-1e70579778ae)

Email in the code editor:
![code_editor](https://github.com/user-attachments/assets/0570fac3-eee5-41d5-97a9-302cdc78df7f)

- Browser: Firefox and Chrome
- SnappyMail Version: 2.36.4 (Nextcloud plugin version)
- Mode: nextcloud

**Comment by the-djmaze** [comment]
Confirmed.
The issue happens one way or the other.
In the past the line endings were duplicated and now they are gone.

The issue is browser content-edit.
There are 2 types of "Enter".
When hitting "Enter" The browser default is `<p>` and that makes paragraphs with "empty line" (margin) between the lines.
You need to use "Shift+Enter" for a `<br>`.

Squire handles it different as it always makes `<div>` blocks.
This is easier regarding the default HTML rules defined by W3C and WHATWG.
As they have semantic differences:
 - `<div>` element is designed to describe a container of data
 - `<p>` element is designed to describe a paragraph of content
 
So the following are allowed:
```html
<div><div></div></div>
<div><p></p></div>
<div><blockquote></blockquote></div>
```
But these NOT:
```html
<p><div></div></p>
<p><table></table></p>
<p><blockquote></blockquote></p>
```

I will see if i can figure out a way to keep `<div></br></div>` or convert to `<p>` where allowed.

**Comment by the-djmaze** [comment]
Also see #1389

**Comment by chsleemsi** [comment]
Sorry that it seems the problem persist.  May I know if there is any solution?
