### ISSUE TITLE
Reddit Digest email is displaying incorrectly

### ISSUE THREAD

**Issue by Zero3K** [the-djmaze/snappymail#184]
Reddit's Digest email is displaying incorrectly. They are not all centered. Here's a screenshot of the issue:

![Screenshot_20220108-124542](https://user-images.githubusercontent.com/6194332/148654295-f6c8ca19-9b4f-4661-b343-ffaf10ffca8d.png)

**Comment by the-djmaze** [comment]
I think this is caused by a change i made in the html parser.
I added removal of `<table width="...">` width attribute because a lot of e-mails i receive have a width that is bigger then my view width.
This causes issues with sidescrolling using your mouse (finger on mobile no problem, but annoying).

The other solution could be converting `width="1080px" to `style="max-width:1080px".

**Comment by Zero3K** [comment]
Its still happening.

**Comment by the-djmaze** [comment]
Could you provide a source of the email (redacted for privacy)?

**Comment by Zero3K** [comment]
Here is what you asked for:

[Should I choose ECE(Eletronics and Commnuinc.txt](https://github.com/the-djmaze/snappymail/files/8061864/Should.I.choose.ECE.Eletronics.and.Commnuinc.txt)

**Comment by eibex** [comment]
I am experiencing a similar issue with PayPal receipts.
The email, which is centered in other email clients, appears on the left side of the preview box.

I would provide a redacted source of the email but it looks like it uses js (or similar) encryption? (weird - older emails' source is in plain text on gmail).

Not sure if you have any PayPal email to test it with, otherwise I will get the source from an email I received on gmail and try to redact it.

**Comment by eibex** [comment]
Works perfectly with the emails that had issues on my end.
The only thing I would add is that on some HTML "text" mails there is no padding on the left causing the characters to start right next to the scrollbar.

Adding some padding (maybe on both sides to keep things centered?) just like for plain text mails would be neat.

Let me know if I should open another issue for this since it's a bit of a digression.

**Comment by the-djmaze** [comment]
> The only thing I would add is that on some HTML "text" mails there is no padding on the left causing the characters to start right next to the scrollbar.

Already done for next release.
