### ISSUE TITLE
Fetchmail support in plugin

### ISSUE THREAD

**Issue by dominiquefournier** [the-djmaze/snappymail#194]
Hi !
I would like to suggest an improvement : it can be cool if we can add a plugin to configure fetchmail.
The user set an external IMAP server, with login and password, fetchmail will get the mails from the external server in the local delivery. Snappymail will only have the interface to store the authentication data in database.

I found https://github.com/PF4Public/fetchmail for Roundcube.

**Comment by the-djmaze** [comment]
> Snappymail will only have the interface to store the authentication data in database.

Well, that´s a problem. Read: https://github.com/the-djmaze/snappymail/releases/tag/v2.9.1
Due to that, all authentication data is encrypted and can't be decrypted by server.

So fetchmail will never work as it stores date passwords in base64(plain text).

**Comment by dominiquefournier** [comment]
I understand well the security break, but it is different from the IMAP authentication data. It is for fetchmail authentication data with a login/password different than the IMAP one.
Of course, the server need to crypt these data to not be theft if there is a database breach.

The object of the proposal is to allow multiple users to provide external accounts like Zimbra and Roundcube do.
I hope you will reconsider the position.

**Comment by the-djmaze** [comment]
I understand, but fetchmail requires plain text passwords.
So users must really know the database is secure enough that nobody can steal the imap plain passwords.

As i described in linked version anyone who has access to server or db backup has the passwords.
That's why i revamped the system to be much more secure.

With fetchmail.pl that is not possible.

A better solution could be that SnappyMail does the import with a script (like fetchmail.pl does) in background when user is logged in.
It also needs a lock file that simultanious account logins don't execute the background script.

Fetchmail is nice for local mailserver/nas in your own house and then i see benefits.

**Comment by the-djmaze** [comment]
Closed as i currently see this as a feature request that someone could write as plugin.
