### ISSUE TITLE
`Ctrl` + `s` shortcut does not save the message in the composition view anymore

### ISSUE THREAD

**Issue by Massedil** [the-djmaze/snappymail#252]
**SnappyMail version, browser, browser version:**

SnappyMail version : 2.13.1
Browser: Mozilla Firefox 97.0 (64 bits) / Ubuntu 20.04

**Expected behavior and actual behavior:**

`Ctrl` + `s` shortcut does not save the message in the composition view anymore.

Actual: The web page is proposed to be saved.
Expected : The mail is saved in the draft folder (like before).

**Steps to reproduce the problem:**

Just click on the new mail button and try to save the draft with `Ctrl` + `s` .

**Comment by the-djmaze** [comment]
Actually it does work, but the problem is `input` elements.
The shortcuts are disabled when the focus is on them.
This is because of conflicting shortcuts,

So, i've changed the code and fixed all shortcuts in a way that disabling the shortcuts system is not needed and they also work in the edit areas.

**Comment by Massedil** [comment]
I can confirm the problem is solved with [v2.13.2](https://github.com/the-djmaze/snappymail/releases/tag/v2.13.2), thanks !
