### ISSUE TITLE
Mobile mode : Can not write new mail

### ISSUE THREAD

**Issue by dominiquefournier** [the-djmaze/snappymail#298]
**Describe the bug**
In mobile mode, on Android 10, when clicking on "new mail" key, the browser go on fullscreen, but do not display the window where we can type the new mail.

**To Reproduce**
1. Go to 'Main page'
2. Click on 'New mail' (the Green button)
3. The browser go in Full screen
4. You don't see the window where you can compose the email
5. You can not go back from full screen too.

If I try "Desktop version" and re-login, I see the window and can type my mail, even in this browser.
If I try to switch to "Desktop version" from "Mobile version", without re-login, I can not open the window

**Mobile :**
 - Browser : stock browser Android 10 Huawei 12.0.1.302
 - SnappyMail Version 2.14.0

**Comment by the-djmaze** [comment]
Actually it's not really resolved.
I had to drop the feature due to a bug in Chrome.

Works:
1. open message
2. make message fullscreen
3. hit reply button
4. It opens the composer nicely in fullscreen

Fails:
1. open composer
2. system requests fullscreen
3. composer window is hidden

It worked before, but something has changed that screws up Chrome behavior.
