### ISSUE TITLE
How to integrate it properly into Plesk Obsidian 18.x?

### ISSUE THREAD

**Issue by jayjupdhig** [the-djmaze/snappymail#311]
So i know, "AfterLogic Webmail" is able to be integrated properly into Plesk... is snappymail also able to to this?

Thx for feedbacks.

**Comment by the-djmaze** [comment]
Doesn't this depend on the effort of Plesk/cPanel  owner Oakley Capital, if they want even more money in their pockets or give their customers more choice?

After all these panels did get very expensive after 2018 (that's why i dropped them and started to use RainLoop).

Or are scriptaculous and others still active?

**Comment by kosuodhmwa** [comment]
I was thinking just to ask, but it's not a real problem to set it up manually so i think! :-)

**Comment by jayjupdhig** [comment]
So closed... (this is my business account)
