### ISSUE TITLE
Save panel width in vertical split layout

### ISSUE THREAD

**Issue by florealcab** [the-djmaze/snappymail#328]
**Is your feature request related to a problem? Please describe.**
On vertical split layout, we can choose the width of the panes (messages list view and message content view). But if we refresh the page (or if we login back), the width of the panes go back to default values.

**Describe the solution you'd like**
Save the width in the user config or in a cookie to keep that value. Best choice should be storing in server side so this config is kept on every client the user has.

**Comment by the-djmaze** [comment]
> Best choice should be storing in server side so this config is kept on every client the user has.

Not really because this has issues when you login on screens with different heights.
Instead, the height could be calculated in %.
But if you change the height on screen 1 this also happens on screen 2.

Browser local storage could be an option, but when you are in private mode (or clear cookies) this will not work either.

Since there is no best, we could just define behavior and just use that, like:
1. store cookie/local AND on server
2. use cookie ELSE from server
3. value is in %

Is that ok?

**Comment by florealcab** [comment]
Seems to be a good option :)
