### ISSUE TITLE
Mail view broken

### ISSUE THREAD

**Issue by kurim** [the-djmaze/snappymail#343]
**Describe the bug**
On some HTML Mails the layout is broken (paypal, goodsmilecompany, lieferando etc)
Maybe they don't follow standards 100% which may cause the issue.

**To Reproduce**
1. open specific mail and compare it with rainloop for example.

**Expected behavior**

**Screenshots**
**Paypal**
Logo position not correct.
```css
#messageItem .b-text-part.html img {
    max-width: 90vw;
    height: auto;
}
```
removing height: auto fix it for paypal, since auto override the image attribute which should happen i guess.
snappymail:
![image](https://user-images.githubusercontent.com/1880220/164659512-5de478a1-5dfa-4bcb-bd0d-bd961e9e4f19.png)
rainloop:
![image](https://user-images.githubusercontent.com/1880220/164660253-1b2342ec-eadf-411b-933f-7c3b93f4306f.png)

**GoodsmileCompany**
Outer Table aligne="center" ignored and width ignored.
snappymail:
![image](https://user-images.githubusercontent.com/1880220/164663199-28e545c4-a33c-4be3-88a3-c39048f0c384.png)
rainloop:
![image](https://user-images.githubusercontent.com/1880220/164662715-cfd9a7d5-e9f7-4203-a8ab-20d71a3c9a77.png)

**Lieferando**
in this case the background image from the <td> is gone.
snappymail:
![image](https://user-images.githubusercontent.com/1880220/164658029-66703f7a-39f1-4e9a-9476-d07416698f63.png)
rainloop:
![image](https://user-images.githubusercontent.com/1880220/164658351-9f18a791-2b85-4ea5-ad5b-b56bdfa25e06.png)

**Desktop (please complete the following information):**
 - Browser Chrome: 100.0.4896.127
 - SnappyMail Version [2.15.0]

Hint:
Tested with and without image proxy

**Comment by the-djmaze** [comment]
Correct, some emails don't look good.
This is because SnappyMail has many changes for better mobile view.

Somehow a lot of email "designers" still think that email is the same as DTP, and then inside the HTML there are many fixed widths and heights.
`cleanHtml` function in https://github.com/the-djmaze/snappymail/blob/master/dev/Common/Html.js tries to "fix" these things by:
* replace attribute `width="N"` with: `style="max-width:N;width:100%"`
* replace attribute `background="…"` with: `style="background-image:url(…)"`
* replace attribute `bgcolor="…"` with: `style="background-color:…"`
* replace attribute `color="…"` with: `style="color:…"`
* remove style properties: behavior, cursor, min-width
* remove elements: form, o:p

If something still has a wrong view, we must find the source in HTML and create a fix in a way so that it also properly works on small screens (like mobile phones).

Do you have the (edited for privacy) source of those emails?

**Comment by kurim** [comment]
thank you for the fast feedback,, here are the mail source only the mail part w/o header, hope it is fine.
[paypal.txt](https://github.com/the-djmaze/snappymail/files/8542283/paypal.txt)
[goodsmile.txt](https://github.com/the-djmaze/snappymail/files/8542284/goodsmile.txt)
[lieferando.txt](https://github.com/the-djmaze/snappymail/files/8542282/lieferando.txt)

your suggestion I will try later.
