### ISSUE TITLE
The "Not-formatted" HTML editor is not used by default when replying to an email

### ISSUE THREAD

**Issue by Massedil** [the-djmaze/snappymail#355]
**Describe and reproduce the bug**

In settings > General > Default text editor, I have chosen "Not-formatted".

If I compose a new email, this rule is respected.

**Actual behavior**

If I reply to an email, the HTML editor is displayed (and I have to disable it to get the "Not-formatted" editor).

**Expected behavior**

If I reply to an email, the "Not-formatted" editor is displayed.

**Note**

In settings > General > Default text editor, If I choose "Not-formatted (forced)", the behavior is like expected when composing a new email and when replying to an email : it is always the "Not-formatted" editor that is used.

**Screenshots**

![image](https://user-images.githubusercontent.com/20357783/165985197-34ec4adb-e7df-4d19-bb5e-2e4df86a4f44.png)

**Desktop (please complete the following information):**
 - Browser Firefox 99
 - SnappyMail Version 2.15.0

**Comment by the-djmaze** [comment]
> If I reply to an email, the HTML editor is displayed (and I have to disable it to get the "Not-formatted" editor).

Correct!

When viewing a message in HTML mode, you are replying in HTML.
When viewing a message in Plain mode, you are replying in Plain.

**Comment by BenAlanSouthall** [comment]
Is this an expected feature? I have encountered the reverse - when I go to reply to a message that is sent in plain text, it defaults to plain over HTML. I now lose proper formatting of my signature, and I don't seem to see an option in the message composer to insert it again if I switch to HTML editing. So our company information in this is lost.

Nearly all mail clients support HTML nowadays, but plain or HTML tends to be a user's set-up. I.e., if I receive a message in plain text, almost certainly someone working with us has set up their client this way, but it's incredibly unlikely they won't be able to support HTML messages.

I believe my preferred setting ought to override the format of the original message, and the same for the OP of this issue - I would prefer always to respond in HTML, irrespective of the sender's message format, and I am assuming it is the OP's preference always to respond in plain text for some particular reason, and that their reason for sticking to this will apply even if they receive an HTML message.

Perhaps the simplest way to control this setting would be to add a third option in the drop-down box. Something along the lines of

Always compose messages in:
- Plain
- The same format as the received message, when replying.
- HTML

Hopefully, I think this might settle the ambiguity.

**Comment by the-djmaze** [comment]
If someone sends you a message as plain/text, wouldn't it prefer that over HTML?

There was an option in RainLoop to select "Force HTML" or "Force Plain".
I removed it because it was using OpenPGP.js v2 and only PGP/Inline that does not support HTML.
So "Force HTML" was pretty useless when using GPG.

However, since SnappyMail now uses OpenPGP.js v5 and supports PGP/MIME (yes HTML supported) those options could be back.
But then you force the recipient (who likes plain/text), to use HTML.
And then the recipient maybe still removes all your HTML and still looks at plain/text.
Then your company information is lost at recipient end.

So the question is: why is your company information lost?
Because my signature is HTML and switching between plain and HTML mine is still valid.
Are you accidentaly using:?
1. images
2. fonts
3. other non-supported HTML markup, read: https://www.outlook-apps.com/html-ignored-by-outlook/ and https://pinpointe.com/blog/email-campaign-html-and-css-support/

**Comment by BenAlanSouthall** [comment]
> If someone sends you a message as plain/text, wouldn't it prefer that over HTML?
No, I would prefer always to reply in HTML. I am confident no-one is going to be contacting us with an account that doesn't support HTML messages; most likely people have similar default setting in their clients and jyst haven't turned them on. 

And in either case, as you say, it's the case of someone's settings need to be applied. It feels a bit unusual to me to prefer the recipient's settings in their client, over use or not of HTML, over mine.Either

- I send a plaintext email (to all recipients) in case one recipient would lose information from HTML
- I send an HTML message to all recipients, and anyone who doesn't support HTML messages then cuts it back to plain text on their end.

And as mentioned, in all cases I highly doubt any recipients in this day and age don't have the ability to support HTML - like a colleague of mine the other day, they most likely have a setting turned on somewhere and don't know where or why this is on.

So there are valid reasons for either, but I would like to be able to choose, that I want to respect my settings over those of the recipient. There would be several ways to do this, but I reckon something like adding a third option to the drop-down would be one simple way of doing it that I believe ought to cover all cases.

Also FYI: we aren't accidentally using images and fonts - those are purposefully placed in the signature in order to display our company logo, and provide consistent branding and feel, along with links to our website and email links, so people can click on an individual name to send a message. Even if there are no guarantees, that's quite common in many emails I receive in my personal life from companies. When it goes to plain text, we lose any markup and just get my name, which doesn't really add the same professionalism.

Thanks

**Comment by Massedil** [comment]
For me, if you receive a plain text message and reply with HTML, you cannot be sure the recipient want HTML (he surely prefers plain text). But, if you have the option to force reply in HTML and you set it, it is normal that you reply with HTML.

If you receive a HTML message and reply with plain text, you can be sure the recipient can read your reply.

For me, the option to "Always compose messages in:" is a good idea to solve our needs.

**Comment by BenAlanSouthall** [comment]
I was thinking, as if you always want plain, and I always want HTML.

Then if I write an email to you, you will always have to respond in HTML.
If you write an email to me, then I will always have to respond in plaintext. 

So I see the logic behind this, but the settings as they are mean neither of us gets our desired format 50% of the time.

Therefore personally I think it's a sensible option for some people, but should be possible to configure just to use the preferred one always.

**Comment by the-djmaze** [comment]
Surprise, there's more 😄 

SnappyMail supports full vCard and Thunderbird has a boolean property `X-MOZILLA-HTML`.
You gues what that does when someone sends you a vCard.

So, just prefer html, plain, auto isn't enough either.
1. Plain when message is
2. HTML when mesaage is
3. HTML when you decide, although message is plain
4. Plain when you decide, although message is plain
5. New message by contact use `X-MOZILLA-HTML` setting?
6. etc. etc.

**Comment by the-djmaze** [comment]
For now i removed the `!message.isHtml()` check.

**Comment by BenAlanSouthall** [comment]
Afraid I've never used a vCard, but not entirely surprising it gets more complicated!! Good find at least :smile:
