### ISSUE TITLE
Download all Attachments of selected Emails

### ISSUE THREAD

**Issue by albsch** [the-djmaze/snappymail#361]
**Is your feature request related to a problem? Please describe.**

It would be nice if I could download all attachments of multiple emails at once.

**Describe the solution you'd like**

*  Select emails you want to download the attachments for

![image](https://user-images.githubusercontent.com/38429047/166190562-b97d28dc-a0d3-4ce7-a819-5af54f8794f2.png)

* Click `Download attachments as zip` under `Forward as attachments`

![image](https://user-images.githubusercontent.com/38429047/166190585-29a1de9f-507e-408b-9a02-8ce42a844529.png)

**Describe alternatives you've considered**

I can't think of a good way to download many selected attachments at once.

**Comment by the-djmaze** [comment]
I understand what you want, but the problem is: define "attachment"

Basically there is:
1. `Content-Disposition: inline` attachments shown in HTML, like images
2. `Content-Disposition: attachment` real attachments NOT shown in HTML

When you view a single message you know which is which.
In a list of subjects you have no idea.

I like `Content-Disposition: attachment` only and mostly it is not a problem, except...

People send you pictures about work/design/party/etc. and you want to store them all in a zip.
The zip might not have all images because some have send the images `inline`.

To prevent confusion both should be zipped and this differs from single view.

So i think this should be discussed a little more.

**Comment by albsch** [comment]
Personally, I would not want to download anything related to inline HTML things and don't see them as attachments.

**Comment by jdaviescoates** [comment]
For a starter could we just have a way to download all the attachments attached (not inline, attached) to a specific email?

Like, somewhere here I should see a button or link which allows me to download all of these attached pictures at once so I don't have to do them all individually:

![image](https://user-images.githubusercontent.com/2113743/191979875-a5813116-c42a-4c6b-a0d9-078b0e2f2a9b.png)

There doesn't seem to be able way to do this at present.

**Comment by the-djmaze** [comment]
@jdaviescoates sorry for the late respones.
On the bottom right of your image is a cog wheel.
Click and you get download options.

**Comment by the-djmaze** [comment]
Added :wink:
