### ISSUE TITLE
many folders on Cyrus IMAP break login

### ISSUE THREAD

**Issue by tkasch** [the-djmaze/snappymail#365]
**Describe the bug**
When trying to log in to an IMAP account of our Cyrus IMAP server (version 3.0.13 as shipped with Ubuntu 20.04) with > 300 folders, login fails after approx. 30 seconds without raising an error.

**To Reproduce**
1. enter valid credentials on login screen
2. after ~30 seconds, the spinner is replaced by a fresh login screen

**Expected behavior**
SnappyMail's UI should appear

**Desktop (please complete the following information):**
 - Browser: Firefox 98.0 on Ubuntu 20.04
 - SnappyMail Version 2.15.1

**Additional context**
As it seems, Cyrus supports **GETMETADATA** but takes too long to complete in time. The log shows:
```
[2022-05-04 10:56:38.732][29a44ec1] IMAP[DATA]: > TAG2 GETMETADATA (DEPTH infinity) "*" ("/shared" "/private")\r\n
[...]
[2022-05-04 10:57:09.044][29a44ec1] IMAP[DATA]: < TAG2 OK Completed\r\n
[...]
[2022-05-04 10:57:09.459][29a44ec1] INFO[TIME]: Time delta: 30.779828071594
```
I'm not sure about other side effects but the following patch seems to mitigate this issue for us:
```
--- /tmp/snappymail/v/2.15.1/app/libraries/MailSo/Imap/Commands/Folders.php	2022-04-30 00:45:25.000000000 +0200
+++ snappymail/v/2.15.1/app/libraries/MailSo/Imap/Commands/Folders.php	2022-05-05 11:07:01.115838394 +0200
@@ -432,6 +432,8 @@
 		// RFC 5464
 		$bMetadata = !$bIsSubscribeList && $this->IsSupported('METADATA');
 		$aMetadata = null;
+		// XXX: Hack to speed up folder enumeration during login
+		$bMetadata = false;
 		if ($bMetadata) {
 			// Dovecot supports fetching all METADATA at once
 			$aMetadata = $this->getAllMetadata();
```

**Comment by tkasch** [comment]
Thanks for the hint, with the change I seem to be able to log in reliably. But it takes approx 18 seconds until the UI appears after entering the credentials. Our users would consider this a significant step backwards, I'm afraid. In our current RainLoop installation, login is instantaneous.

**Comment by the-djmaze** [comment]
> In our current RainLoop installation, login is instantaneous.

Difference is that SnappyMail fetches all folders info at once where RainLoop did not.
This means:
- read/unread messages
- metadata

This is based on IMAP capabilities: LIST-STATUS and METADATA

What happens if you fake the system that LIST-STATUS is not available?
Say:
snappymail/v/2.15.1/app/libraries/MailSo/Imap/ResponseCollection.php
```php
	public function getCapabilityResult() : ?array
	{
// ....
			if (\is_array($aList) && \count($aList)) {
				$aList = \array_map('strtoupper', $aList);
				\sort($aList);
//				return $aList;
				return \array_diff($aList, ['LIST-STATUS']);
			}
```

**Comment by tkasch** [comment]
>```
> 				return \array_diff($aList, ['LIST-STATUS']);
> ```
I've tried logging in with this modification a few times and it doesn't seem to make much difference "Time delta" in the logs varies from 12-20 seconds...
> ```
> 				return \array_diff($aList, ['LIST-STATUS','METADATA']);
> ```
... but dropping `METADATA` indeed makes a huge difference and brings the login time below 1 second. :-)

What would be the downside of not having the folders' metadata available in SnappyMail?

**Comment by the-djmaze** [comment]
> What would be the downside of not having the folders' metadata available in SnappyMail?

With this extension you can assign information to folders.
For example:
* /private/comment = "This is my comment for this folder"
* /private/specialuse = "\Trash" [rfc6154](https://www.rfc-editor.org/rfc/rfc6154.html)
* /private/vendor/kolab/folder-type = "contact"

Kolab isn't 100% supported, but could be in the future.
When Kolab is used, this is important because certain IMAP folders will then NOT contain mail.
Instead it will store Kolab data like contacts, calendar, tasks, etc.
And then SnappyMail will ignore those folders for mail messages (view, copy, save, etc. etc.)

If you don't support Kolab, it would be better to disable METADATA in Cyrus.
However, on Google i could not find an option to disable it in Cyrus.
Instead, maybe your `metapartition`/`metapartition_files` options are not on a high-speed partition?

When this all is an issue for your setup, we might could think about moving the METADATA tasks to a background process with caching.
This allows faster responses but as downside the METADATA could be not up-to-date.

**Comment by tkasch** [comment]
> If you don't support Kolab, it would be better to disable METADATA in Cyrus. However, on Google i could not find an option to disable it in Cyrus. Instead, maybe your `metapartition`/`metapartition_files` options are not on a high-speed partition?

We don't deploy Kolab but I'm not sure right now if some users run IMAP clients that make use of METADATA. I'll try to retrieve that information from our Cyrus installation. But METADATA does indeed not seem to be a configurable option, at least not in the version we're currently running.

> When this all is an issue for your setup, we might could think about moving the METADATA tasks to a background process with caching. This allows faster responses but as downside the METADATA could be not up-to-date.

That sounds like a good long-term solution, at least for our setup. But our primary goal is to replace RainLoop ASAP, so I would be willing to live with a manual/local modification at out site for the time being...

**Comment by tkasch** [comment]
I've tried merging 06c0666 into my test installation and it seems to work -- almost. There's probably a cleaner/better way, but something like the following change to `setCapabilities()` seems to be necessary to make the application's config available in that function:

```
--- a/snappymail/v/0.0.0/app/libraries/MailSo/Imap/ImapClient.php
+++ b/snappymail/v/0.0.0/app/libraries/MailSo/Imap/ImapClient.php
@@ -294,7 +294,7 @@ class ImapClient extends \MailSo\Net\NetClient
        private function setCapabilities(ResponseCollection $oResponseCollection) : void
        {
                $aList = $oResponseCollection->getCapabilityResult();
-               if ($aList && $this->__DISABLE_METADATA) {
+               if ($aList && \RainLoop\Api::Config()->Get('labs', 'imap_disable_metadata')) {
                        // Issue #365: Many folders on Cyrus IMAP breaks login
                        $aList = \array_diff($aList, ['METADATA']);
                }
```
