### ISSUE TITLE
Number of new emails not listed in tab title

### ISSUE THREAD

**Issue by Pumpino** [the-djmaze/snappymail#380]
When Rainloop has unread emails, the tab title in the browser changes from `user@domain.com` to `(3) user@domain.com` to indicate that there are three unread emails.

This is really useful, as when I'm working in a different tab, I can see the title of the Rainloop tab change to indicate that there are three new messages.

However, I realised that SnappyMail doesn't do this. The only way to check for new mail is to make the tab active. Is there a reason this feature was removed?

**Comment by the-djmaze** [comment]
SnappyMail has a worker that should use the OS notification system.
When active, you should get an OS native message when new messages arrive.

> Is there a reason this feature was removed?

Yes, on most browsers the tabs are very small.
On mobile browsers you don't even see the tabs at all.
Too see the `(3)` is not much, that's why SnappyMail uses the OS notification system.
