### ISSUE TITLE
show the number of unread mails on all mail addresses/accounts

### ISSUE THREAD

**Issue by grufocom** [the-djmaze/snappymail#437]
I use snappymail with a lot of mail accounts and I can't see when I get new mails on any of my accounts - so I have to click through all my accounts to see the new mails.

check per interval (1 minute or more) all accounts for new mails in the input folder and show a symbol when there are new mails, would be great to see per account how many new mails arrived.

thx, great work so far! :-)

**Comment by the-djmaze** [comment]
It was (disabled) in the RainLoop code so i've removed it.

When you think about it, it would be wise to not do this by default in a webmail application.
As the load strain on the server could be huge, due to checking all folders of all accounts could take minutes.

I might add something like `accounts_count_all` in application.ini to make this optional for people who own the server and know what they are doing.

**Comment by grufocom** [comment]
that's right, the load of checking all folders every minute might be too high. however, i would only check the inbox folders and ideally give the option to select the accounts to be checked.

A default value of 10 minutes or so would also reduce the load.

For me, it would only be important to see when new mails arrive in my inbox and not have to click through each account individually.

in my case it would also be my own mail server ;-)

**Comment by Mer0me** [comment]
I think this feature is important as all desktop mail clients are doing this. I would like to see it in SnappyMail too.

**Comment by the-djmaze** [comment]
Added as: fetch each account only once between 3 and 30 seconds
