### ISSUE TITLE
auto-selection of next message after deletion not working

### ISSUE THREAD

**Issue by kurti500** [the-djmaze/snappymail#440]
**Describe the bug**
After deleting a message, there is no other message selected afterwards 

**To Reproduce**
1. Highlight/select a message (dark blue (brown if unread) bar on left hand side), mail content visible in preview pane
2. Click on "delete" icon
3. Message is deleted, but no other message is afterwards active/shown, preview pane empty

**Expected behavior**
I would expect that the next older message is highlighted/preselected and also shown in preview pane 

**Screenshots**
Step1, message selected
![image](https://user-images.githubusercontent.com/82444848/173627684-97ca4657-ae19-4714-8508-1624e67e554f.png)
After step3, no message selected, preview pane empty
![image](https://user-images.githubusercontent.com/82444848/173627851-91f21235-79fc-4a33-8843-bfa8f6545b26.png)
![image](https://user-images.githubusercontent.com/82444848/173627872-9f05d058-72d2-4375-9c88-2541a6a8cfcd.png)

**Desktop (please complete the following information):**
 - Browser Chrome Version 102.0.5005.63 (Official Build) (64-bit)
 - SnappyMail Version 2.16.3

**Additional context**
On latest Rainloop, it worked as expected, the next oldest message was automatically preselected and displayed in preview pane after deletion.
Do I miss configuration/parameter/setup to have Snappymail work as expected, or is the current behavior the one to be expected?

**Comment by the-djmaze** [comment]
SnappyMail does a best effort to be "mobile first".
In this case there are several things to think about:
* battery usage/drain
* mobile network data limits

When selecting a message, the mentioned points are in effect.
Secondly, maybe you don't want to (always) see the next message? (user preference, indeed)

As a result you could see this as "works as expected" because there are conflicts:
* user preference: yes/no
* mobile network: yes/no
* mobile cpu/battery: yes/no

**Comment by kurti500** [comment]
All right, indeed I personally would prefer it the other way round, but I understand the concept/concern.
Maybe this can be revisited in case other/more users prefer it the other way ;-)
Will close the issue.
Thanks for checking.
