### ISSUE TITLE
migration from rainloop to snappymail

### ISSUE THREAD

**Issue by andy-mic** [the-djmaze/snappymail#444]
**Describe the bug**
I have recently come across snappymail as rainloop appears to no longer be in development.
I have read the install instructions (https://github.com/the-djmaze/snappymail/wiki/Installation-instructions) but am having trouble getting snappymail to work.  I have tried both 'over the top' of an existing install, as well as a build from scratch.

I must admit I'm quite new to this, so there is a good chance I've missed something.  The documentation is quite brief, so perhaps additional steps/details may need to be included? 

**To Reproduce**
I have followed the instructions under "Migration/Upgrade from RainLoop"  - I don't use any plugins - when I try to access the admin page, I just get a blank page

I have also tried installing on a new system "General instructions" (fresh OS image, etc.) and still get the same blank page

The URLs I have tried (x.x.x.x is the IP of the server)
http://x.x.x.x/webmail?admin  - The requested URL was not found on this server.
https://x.x.x.x/webmail?admin  - The requested URL was not found on this server.
http://x.x.x.x/?admin  - blank page
https://x.x.x.x/?admin  - blank page
http://x.x.x.x/     - blank page
https://x.x.x.x/    - blank page

Sample apache config (after OS + snappymail fresh install)

/etc/apache2/sites-available/webmail.conf

```
<VirtualHost *:80>
  ServerName my.server
  Redirect / https://my.server
</VirtualHost>

<VirtualHost *:443>
  ServerName my.server
  DocumentRoot "/var/www/webmail/"
  SSLEngine On
  SSLCertificateFile    /etc/ssl/certs/ssl-cert-snakeoil.pem
  SSLCertificateKeyFile /etc/ssl/private/ssl-cert-snakeoil.key
  #ServerAdmin postmaster@mydomain.com

  ErrorLog "/var/log/apache2/webmail_error_log"
  TransferLog "/var/log/apache2/webmail_access_log"

<Directory /var/www/webmail>
  DirectoryIndex index.php
  Options -Indexes +ExecCGI
  AllowOverride All
  Order deny,allow
  Allow from all
  Require all granted
</Directory>

</VirtualHost>
```

**Expected behavior**
Access to the admin page to configure snappymail

**Desktop (please complete the following information):**
 - Browser Firefox & Edge
 - SnappyMail Version 2.16.3

**Other info**
- Debian 11 bullseye
- Apache web server

**Comment by xgbstar1** [comment]
Hello. Do you know how to use Docker?

If so, try below steps that I used to get this to work. Otherwise, hopefully these provide you with a sense of steps that work.

0. Create a working directory and add the following directory structure and files
```
— Dockerfile // see step 1. for details
— run.sh  // see step 2. for details
— volumes
—— etc-apache2-sites-available
——— snappymail.conf  // see step 3. for details
—— usr-local-etc-php-conf.d
——— increase-upload-size.ini  // see step 4. for details
—— var-log-apache2
——— // optional: migrate log files from Rainloop here
—— var-www-snappymail-data
——— // optional: migrate data files from Rainloop here, includes files like "VERSION", index.html, index.php, etc. and folder named "_data_" 


1. Create a working directory and add a new file named `Dockerfile` with the following content. Note, the customizations.css file is optional and you can take out the related lines if you don't plan to customize the css. I'm happy to share my customizations based on Rainloop if you're interested.

```Dockerfile
FROM php:7.4-apache

RUN apt-get update && \
apt-get install -y unzip wget

RUN  curl -s https://api.github.com/repos/RainLoop/rainloop-webmail/releases/latest \
| grep "browser_download_url.*rainloop-community.*zip" \
| cut -d : -f 2,3 \
| tr -d \" \
| wget -qi - 

COPY ./volumes/etc-apache2-sites-available/snappymail.conf /etc/apache2/sites-available/snappymail.conf

RUN unzip rainloop-community*zip -d /var/www/snappymail

RUN curl -s https://api.github.com/repos/the-djmaze/snappymail/releases/latest  \
	| grep "browser_download_url.*snappymail.*zip" \
	| cut -d : -f 2,3 \
	| tr -d \" \
	| wget -qi -

RUN unzip -o snappymail*zip -d /var/www/snappymail

COPY css-customizations/customizations.css  /tmp/customizations.css

RUN cat /tmp/customizations.css >> /var/www/snappymail/snappymail/v/2.16.3/static/css/app.min.css

RUN chown www-data:www-data /var/www/snappymail/ -R

RUN a2ensite snappymail.conf

RUN a2enmod rewrite && \
    a2enmod ssl
```


2. Add `run.sh` file
```bash
#!/bin/bash

pushd /opt/snappymail

docker build -t snappymail .

docker rm -f snappymail

id=$(docker create snappymail)

docker cp $id:/var/www/snappymail/data/. $(pwd)/volumes/var-www-snappymail-data

docker rm -v $id

find $(pwd)/volumes/var-www-snappymail-data -type d -exec chmod 775 {} \;
find $(pwd)/volumes/var-www-snappymail-data -type f -exec chmod 664 {} \;

chown -R 33:33 $(pwd)/volumes/var-www-snappymail-data

docker run -it \
	-d \
       	-p 80:80 \
	--restart unless-stopped \
	-p 443:443 \
	-v $(pwd)/volumes/var-www-snappymail-data:/var/www/snappymail/data \
	-v $(pwd)/volumes/etc-apache2-sites-available:/etc/apache2/sites-available \
	-v $(pwd)/volumes/var-log-apache2:/var/log/apache2/ \
  -v $(pwd)/volumes/usr-local-etc-php-conf.d/increase-upload-size.ini:/usr/local/etc/php/conf.d/increase-upload-size.ini \
	-v /etc/letsencrypt/:/etc/letsencrypt/:ro \
	--name snappymail \
	snappymail

popd

```

3. Add the `volumes/etc-apache2-sites-available/snappymail.conf` file. These instructions reference an SSL certificate generated for `mail.YOURDOMAIN.com` be `letsencrypt` so update this configuration to your needs. Also, the `ServerName` should be updated accordingly.
```apache
<VirtualHost *:80>
  DocumentRoot "/var/www/snappymail/"
  ServerName mail.YOURDOMAN.com
  LimitRequestLine 65536
  ErrorLog "/var/log/apache2/snappymail_error_log"
  TransferLog "/var/log/apache2/snappymail_access_log"
  Options +Indexes +FollowSymlinks
  RewriteEngine on
  Redirect permanent / https://mail.YOURDOMAN.com/
  RewriteCond %{HTTPS} off
  RewriteRule (.*) https://mail.YOURDOMAIN.com%{REQUEST_URI}
</VirtualHost>
<VirtualHost *:443>
  ServerName mail.YOURDOMAIN.com
  DocumentRoot "/var/www/snappymail/"

  LimitRequestLine 65536

  ErrorLog "/var/log/apache2/snappymail_ssl_error_log"
  TransferLog "/var/log/apache2/snappymail_ssl_access_log"


  SSLEngine on
  SSLHonorCipherOrder on
  SSLProtocol all -TLSv1.1 -TLSv1 -SSLv2 -SSLv3
  SSLCipherSuite          ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA
  SSLHonorCipherOrder     on
  SSLCompression          off

  <Directory />
    Options +Indexes +FollowSymLinks +ExecCGI
    AllowOverride All
    Order deny,allow
    Allow from all
    Require all granted
  </Directory>

  <Directory /var/www/snappymail/data>
     Require all denied
  </Directory>

  SSLCertificateFile /etc/letsencrypt/live/mail.YOURDOMAN.com/fullchain.pem
  SSLCertificateKeyFile /etc/letsencrypt/live/mail.YOURDOMAIN.com/privkey.pem

</VirtualHost>
```


4. Add the `volumes/usr-local-etc-php-conf.d/increase-upload-size.ini` file
```ini
upload_max_filesize = 2000M
post_max_size = 2000M;
```

Hope this helps :-)

**Comment by andy-mic** [comment]
I've had a few attempts at installing but still can't get it to work.  The documentation here is very brief and not entirely helpful...hopefully someone is able to point me in the right direction? I'm tearing my hair out trying to get this working :(

I've done a lot of googling and this is what I've done so far:

Fresh install of Debian 11
System update/upgrade
Installed PHP 7.4 (sudo apt-get install php7.4)
Installed Apache (sudo apt-get install libapache2-mod-php)
Installed mbstring (sudo apt-get install php-mbstring)
Enabled zlib (nano /etc/php/7.4/apache2/php.ini)
`zlib.output_compression = On`
Installed json (sudo apt-get install php-json)
Installed libxml (sudo apt-get install libxml2)
Installed dom (sudo apt-get install php-xml)

At this point I can see the default apache webserver page when I browser to the server IP

Downloaded latest version of Snappymail (v2.21.0)
Installed/extracted to /var/www/webmail

Set permissions
```
find /var/www/webmail -type d -exec chmod 755 {} \;
find /var/www/webmail -type f -exec chmod 644 {} \;
chown -R www-data:www-data /var/www/webmail
```

Created a basic webserver config in /etc/apache2/sites-enabled/snappymail.conf
```
<VirtualHost *:80>
  ServerName my.ip
  Redirect / https://my.ip
</VirtualHost>

<VirtualHost *:443>
  ServerName my.ip
  DocumentRoot "/var/www/webmail/"
  SSLEngine On
  SSLCertificateFile    /etc/ssl/certs/ssl-cert-snakeoil.pem
  SSLCertificateKeyFile /etc/ssl/private/ssl-cert-snakeoil.key
  #ServerAdmin postmaster@mydomain.com

  ErrorLog "/var/log/apache2/webmail_error_log"
  TransferLog "/var/log/apache2/webmail_access_log"

<Directory /var/www/webmail>
  DirectoryIndex index.php
  Options -Indexes +ExecCGI
  AllowOverride All
  Order deny,allow
  Allow from all
  Require all granted
</Directory>

</VirtualHost>
```

Enable the site
sudo a2ensite snappymail.conf

Attempt to browse the site, I get a bank page, just as I did previously...

The following error appears in webmail_error_log :
`[php7:error] [pid xxxx] [client xxx.xxx.xxx.xxx:xxxx] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function SnappyMail\\Log::warning(), 1 passed in /var/www/webmail/snappymail/v/2.21.0/app/libraries/RainLoop/Config/Application.php on line 44 and exactly 2 expected in /var/www/webmail/snappymail/v/2.21.0/app/libraries/snappymail/log.php:16\nStack trace:\n#0 /var/www/webmail/snappymail/v/2.21.0/app/libraries/RainLoop/Config/Application.php(44): SnappyMail\\Log::warning()\n#1 /var/www/webmail/snappymail/v/2.21.0/app/libraries/RainLoop/Api.php(35): RainLoop\\Config\\Application->Load()\n#2 /var/www/webmail/snappymail/v/2.21.0/app/libraries/RainLoop/Api.php(92): RainLoop\\Api::Config()\n#3 /var/www/webmail/snappymail/v/2.21.0/app/libraries/RainLoop/Api.php(13): RainLoop\\Api::SetupDefaultMailSoConfig()\n#4 /var/www/webmail/snappymail/v/2.21.0/include.php(164): RainLoop\\Api::Handle()\n#5 /var/www/webmail/index.php(11): include('/var/www/webmai...')\n#6 {main}\n  thrown in /var/www/webmail/snappymail/v/2.21.0/app/libraries/snappymail/log.php on line 16`
