### ISSUE TITLE
Add an option to hide the unread mail count next to the spam folder

### ISSUE THREAD

**Issue by chascode** [the-djmaze/snappymail#457]
Some email providers (Microsoft) do not let you automatically mark spam as read and it's tedious seeing an unread mail count next to the spam folder.

I would like an option to hide the unread mail count for specific folders on the "Folder List" page under settings.

I've considered doing bodge jobs in the source code but it's not clear how to hide the unread count next to one folder.

In the following screenshot the number "2" displayed next to "Spam" is very distracting:

![distracting](https://user-images.githubusercontent.com/52451714/179398794-19efed81-962a-4f2b-80b8-070d587662f6.png)

**Comment by the-djmaze** [comment]
I understand you completely, but always hiding it is also a problem.
Many people i know, have no clue that a valid "new email" might be delivered in the Spam box.

RainLoop did have an option, when there are 50+ folders/mailboxes (configurable), to select which folders are checkable (read/unread counts).
That way the unread counter was not visible for unselected folders.
That feature was removed due to a different (faster) way of fetching the folders list and already have the unread count.

To accommodate all the user wishes and prevent people for not finding new messages (as delivered in spam box, which Microsoft likes to do). An option could be added to the folders settings to hide `unread` for any folder you want.

**Comment by the-djmaze** [comment]
Ok, this makes SnappyMail way to complicated, so i won't add it.
