### ISSUE TITLE
[Cosmetic] Improve the desktop view (b-footer and alignment)

### ISSUE THREAD

**Issue by Massedil** [the-djmaze/snappymail#460]
***b-footer***

In the desktop view, there is a bottom `b-footer` that is empty (purple arrow in the picture). 
If it is used sometimes, can it be hidden if empty ? And if it is not used, can it be removed ?

***alignment***

There is maybe also some blocks that can be better aligned together (green arrows). 
What do you think about that ?

![1](https://user-images.githubusercontent.com/20357783/179750594-4f70f53e-24fb-4a1f-b999-311d8f0b169e.png)

**Comment by the-djmaze** [comment]
> _**b-footer**_
> 
> there is a bottom `b-footer` that is empty (purple arrow in the picture). If it is used sometimes, can it be hidden if empty ?

It is used for two things (when applicable): pagination & quota

You can test "hidden" with:
```css
.messageList .b-footer {
	padding: 0
}
.messageList .b-footer > * {
	padding: 7px
}
```

> _**alignment**_
> 
> There is maybe also some blocks that can be better aligned together (green arrows). What do you think about that ?

This is RainLoop by design, it makes the messages list "stick out (3d)" more to the front.
You can write your own theme that uses the above and your alignment changes, to make it more as you want.
Read: https://github.com/the-djmaze/snappymail/wiki/Custom-Themes

**Comment by Massedil** [comment]
Thanks ! I will look at the custom theme creation.
