### ISSUE TITLE
Add a right-click menu

### ISSUE THREAD

**Issue by Massedil** [the-djmaze/snappymail#461]
It can be really practical to have a right-click menu with some options : 
- Reply / Reply to all / Transfer
- Archive / Spam / Delete
- Move to a folder
- Mark as read / unread

**Comment by the-djmaze** [comment]
There is the [context event](https://developer.mozilla.org/en-US/docs/Web/API/Element/contextmenu_event), but that has drawbacks:
* it prevents the default context menu
* because bad webdesign disables the context menu, you can prevent them with `dom.event.contextmenu.enabled = false` 
And because of stupidity there are browser plugins like:
https://addons.mozilla.org/nl/firefox/addon/re-enable-right-click/

So, somewhere in the past there was a great HTML5 feature [contextmenu attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contextmenu).
It allowed what you want: add items to the context menu!
But it is obsolete because only Firefox supported it.

And now there's a problem: there is no good alternative to create a right-click menu :crying_cat_face:

**Comment by jsonoctopus** [comment]
> And now there's a problem: there is no good alternative to create a right-click menu 

Perhaps the well appreciated right click app for Nextcloud has interesting php code to look at ?  https://apps.nextcloud.com/apps/files_rightclick

**Comment by the-djmaze** [comment]
@jsonoctopus sorry, that code is bad by design.
It "disables" the browser context menu, as i said.

As example:
1. view a message with images and/or links
2. right click image/link to get the browser context menu options

Custom right-click menu:
1. view a message with images and/or links
2. right click image/link = No context menu

**Comment by Massedil** [comment]
> it prevents the default context menu

I think you can always access the browser context menu with "Maj" + "Right click", without any plugin. 

Maybe we can inform snappymail users with a one time message, the first time the new snappymail context menu is displayed, that explains : 
- they can disable the new snappymail context menu function if they want
- they can always access the browser context menu with "Maj" + "Right click"

And add in the new snappymail context menu interface a "help icon" that display again this message ?

What do you think about that ?

**Comment by Massedil** [comment]
> right click image/link = No context menu

To improve user experience, maybe we can also display only the new context menu when the right click is on emails and disable it when it is inside email content ?

So that you always can right-click a link or an image.

**Comment by the-djmaze** [comment]
> I think you can always access the browser context menu with "Maj" + "Right click", without any plugin. Am I wrong ?

No idea, i will test that option.

**Comment by Mer0me** [comment]
I can confirm that under firefox the shift-right-click allow to see the browser built-in context menu

**Comment by ner00** [comment]
If implemented, ideally the context menu should only work while hovering specific areas of the webmail (message list, folder list, contact list, etc), somewhat like Roundcube's context menu plugin: https://github.com/johndoh/roundcube-contextmenu/

**Comment by the-djmaze** [comment]
Since it will not work on touch screens, i won't work on this.
