### ISSUE TITLE
Add Mailto to snappymail : allow to disable the request bar in preferences

### ISSUE THREAD

**Issue by dominiquefournier** [the-djmaze/snappymail#495]
**Is your feature request related to a problem? Please describe.**
On the top of browser bar, there is "Ajouter 'server' comme application pour les liens mailto ? Ajouter l'application" (I can translate this by "Add 'server' for application to mailto links")

**Describe the solution you'd like**
Can we have a user preference to disable this ? I do not want to use snappymail to manage my mails by default and I would like to not see this bar

**Additional context**
![Capture d’écran du 2022-08-19 08-20-32](https://user-images.githubusercontent.com/4428121/185556164-8ddc7fac-b0c4-4a5e-80dd-f43cc630b60d.png)

**Comment by the-djmaze** [comment]
This feature only gives the browser an additional option for `mailto:` links in HTML.
Say, you click on a webpage on the `<a href="mailto:...">` then the browser asks which mail app you want to use for sending the e-mail.

So it doesn't manage your mails.

**Comment by dominiquefournier** [comment]
Thanks ! I click on the button, and it doesn't display the popup anymore.
Sorry for the noise

**Comment by relikd** [comment]
I am in favor of adding an admin option to disable that behavior. I have a mail account which has 4 other email adresses attached. Each time I switch from one account to the other, the popup will show. Since I dont want to add the mail handler to my browser preferences I click the X button. However, this does nothing and the popup will appear again and again.

![screen](https://user-images.githubusercontent.com/1321720/199958782-5d6a8b61-aa24-4ad8-af32-3ff519eec3b2.jpg)

Further, I would need to teach every user how to disable the popup in their individual browser settings (honestly idk if that is possible).
