### ISSUE TITLE
Plugin custom-login-mapping not configurable

### ISSUE THREAD

**Issue by ervee** [the-djmaze/snappymail#5]
**RainLoop version, browser, OS:**
1.14.0-djmaze4, Firefox, Chrome

**Expected behavior and actual behavior:**
I'd like to configure the custom-login-mapping plugin but the plugin settings pop-up won't show.

**Steps to reproduce the problem:**
In admin panel > Packages > Install package "Custom Login Mapping 1.0"
In admin panel > Plugins > Enable plugins and enable the "custom-login-mapping" plugin.
Try to configure the custom-login-mapping plugin by clicking on it.

**Logs or screenshots:**
n/a

Hi, fist of all thank you for modifying this software. It looks very promising! I found it via GoT :)

I'm (beta) testing it besides the regular RainLoop latest version and I ran into the problem above so I thought to share this with you.

Ralf.

**Comment by the-djmaze** [comment]
Correct, because plugins are downloaded from the RainLoop server and that is not PHP 7 compatible.
`PHP Fatal error:  Declaration of CustomLoginMappingPlugin::configMapping() must be compatible with RainLoop\Plugins\AbstractPlugin::configMapping(): array`

Therefore try these: https://github.com/the-djmaze/rainloop-webmail/tree/master/plugins

**Comment by the-djmaze** [comment]
Implemented our own plugin/packages repo

**Comment by ervee** [comment]
Confirmed working now
