### ISSUE TITLE
Re-license as MIT

### ISSUE THREAD

**Issue by istiak101** [the-djmaze/snappymail#509]
Apparently RainLoop team released v1.17.0 few hours ago and re-licensed the project to MIT from AGPL.

https://github.com/RainLoop/rainloop-webmail/pull/2187
https://github.com/RainLoop/rainloop-webmail/releases/tag/v1.17.0

Can Snappymail also re-license this as MIT?

**Comment by istiak101** [comment]
Sorry!
https://github.com/the-djmaze/snappymail/commit/a146d73f4b20eb21cbb43059f47158404859e58b

**Comment by anarcat** [comment]
well it's not because RL relicensed as MIT that you *also* need to follow suit. from what i understand, snappymail is a fork of the AGPL code and as long as you don't reuse the MIT code, you are under absolutely no obligation to relicense your own copy.

now, of course, if you merged that tag in, you should probably switch some of the code to MIT, namely the code that you merged, but even that is kind of an edge case: i would argue that you probably could keep the snappymail licensed as AGPL as long as you comply with the conditions of the MIT license, which is:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

So, weirdly, you could have snappymail licensed as AGPL as long as you ... keep a copy of the MIT permission notice as well. In effect, it would be licensed both as MIT and AGPL (which would make the latter kind of moot).

Anyways, point is: there's a way to keep SnappyMail AGPL if you want to, just don't merge the rainloop code from the MIT commit onwards.

**Comment by istiak101** [comment]
Nope. This is not simply following RL because RL re-licensed this as MIT. I would simply call any *GPL code a pest to opensource in modern age. It worked earlier but in modern times GPL is more harmful than it does any real good. There is no obligation for Snappymail to re-license this to MIT nor keep the new license file. Also if picked from the last tag this can be kept as completely MIT. However I doubt RL followed proper procedure to re-licence and took permission from contributors.

**Comment by anarcat** [comment]
On 2022-09-01 07:21:24, Ice Lake wrote:
> Nope. This is not simply following RL because RL re-licensed this as
> MIT. I would simply call any *GPL code a pest to opensource in modern
> age. It worked earlier but in modern times GPL is more harmful than it
> does any real good.

I'm just going to mention, in passing, that the GPL is probably what
ushered the modern computing age as we know it. But what do I know, I'm
just an old man yelling at the cloud...

> There is no obligation for Snappymail to re-license this to MIT nor keep the new license file. Also if picked from the last tag this can be kept as completely MIT. However I doubt RL followed proper procedure to re-licence and took permission from contributors.

Agreed, it seems that was just YOLO'd and switched. I suspect completely
disregarding the rights of past contributors.

Which also makes it a liability for the SnappyMail project, just
saying. I think it would be safer to not relicense the code, at least
not without getting prior consent of others.

But I'm not a lawyer and it seems my time will be better spent working
on some other projects.

Good luck with the fork!

-- 
One of the things the Web teaches us is that everything is connected
(hyperlinks) and we all should work together (standards). Too often
school teaches us that everything is separate (many different
'subjects') and that we should all work alone.  - Aaron Swartz

**Comment by the-djmaze** [comment]
@anarcat is right, i should have looked carefully when merging RainLoop v1.17
It's reverted.

**Comment by the-djmaze** [comment]
@tuxayo i see
But even if all RainLoop contributors agree, also everyone here must agree.

**Comment by tuxayo** [comment]
> But even if all RainLoop contributors agree

Lol I didn't though so many people would agree in the upstream ticket. I was hoping part would disagree to the possibility of their work to be made proprietary. wtf. How naive I was overestimate the share of people actually caring for libre software. And thus opposing the transition from a copyleft to a permissive license.
Even though, there is still a fair share of people not responding and thus the change can't be legal without a significant work to remove/replace their contributions.

> also everyone here must agree.

Which I hope won't happen but won't have much illusions about that.
