### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by relikd** [the-djmaze/snappymail#564]
**Describe the bug**
SnappyMail can not display an email properly which works fine in Rainloop. External images are disabled for both plugins. It seems SnappyMail does two things differently:
- First, it does not hide the to-be-loaded images and instead shows the long links.
- Second, SnappyMail does not seem to load or apply the stylesheet. A quick search through the email source does not reveal any external sources for the style, must be all inline or defined in head.

If needed I can provide the email source.

**Screenshots**
With Rainloop:
![1](https://user-images.githubusercontent.com/1321720/196692847-d0d2c50f-95f5-4b49-b4c7-a87434d2990c.jpg)

With SnappyMail:
![2](https://user-images.githubusercontent.com/1321720/196692866-67a77a99-b7fe-4d9b-b5ed-aa796086d4b6.jpg)

**Please complete the following information:**
- Browser: Firefox 105
- SnappyMail Version: 2.19.1

**Comment by the-djmaze** [comment]
Correct. SnappyMail shows info about the hidden images on purpose, where RainLoop does not.
The reason behind this has several reasons:
- give users an indication where the hidden images are
- give users information about the hidden images (filename, possible tracking url, etc.)

The "long links" you refer to indicate that they are tracking images and that you should avoid clicking "Bilder anzeigen".
Else the text should be much shorter.

However, maybe i can add a max-width with ellipsis to it.

Secondly, SnappyMail indeed removes all `<style>`sheets.
The problem is that they may conflict with the whole application because the mail is not rendered in an iframe.
RainLoop does the same thing.

**Comment by relikd** [comment]
There is no tracking to be removed, sadly. This email is from a typical newsletter provider (in this case send-in-blue). Nowadays these providers replace _all_ links with tracking links so that the newsletter transmitter gets their statistics. You can't even disable this tracking "feature" (tried that for my newsletter provider ...).

But I must disagree on the stylesheet issue. Rainloop must do something differently because the email is displayed properly there. You can see the missing padding and blue font in the button for SnappyMail whereas Rainloop looks fine. What is more likely, that disabling styles will break the email format or that enabling styles will break the UI? And how could we circumvent this problem then? Could we add an iframe for the Email preview? Or have very unique css classes for snappy? I wonder how Rainloop has solved this problem.

**Comment by the-djmaze** [comment]
SnappyMail removes a lot because of the "dark mode" it has.
There's even a user setting to remove all text and background colors!

In the past there were several view issues with e-mails and some were mine to solve and others by the sender.
Mostly because the sender wrote invalid HTML/CSS that screwed up big time.

If you provide the email source i can have a look why yours is failing.

**Comment by relikd** [comment]
[email.eml.txt](https://github.com/the-djmaze/snappymail/files/9823766/email.eml.txt)

**Comment by the-djmaze** [comment]
Found 2 to solve.

The HTML source does have issues though.
I found `<a><p>` which is not valid HTML.

**Comment by the-djmaze** [comment]
Also added stripping of SendInBlue image tracking

**Comment by relikd** [comment]
Regarding `<a><p>`, it may feel weird but is actually fine with the standard (using HTML5 or "HTML 4.01 + RDFa 1.1" as Doctype)
https://validator.w3.org/#validate-by-input
```html
<!DOCTYPE html>
<html lang="en">
<head><title>#</title></head>
<a href="#"><p>Lorem Ipsum</p></a>
</html>
```
And if you argue that a strict HTML 4.01 is required for older browsers, then I'd argue that SnappyMail does not support old browsers (I get a browser-update warning on my 6y old smartphone).

...

With 2.19.2 it looks better but is still cluttered. If I had an option, I would disable the display-hidden-images altogether.

![screen](https://user-images.githubusercontent.com/1321720/197209975-3ff1e236-fb4e-4c22-aa60-e07cddc9f787.jpg)
