### ISSUE TITLE
PGP Decryption / Encryption Failures

### ISSUE THREAD

**Issue by HeyVern** [the-djmaze/snappymail#600]
**Describe the bug**
Using PGP with the recent versions of Snappymail (both Nextcloud and Docker) seems to break PGP.  There are a couple of issues.  Decryption of PGP emails doesn't seem to work.  I get the button that prompts for decryption, but when the appropriate key is entered, the contents of the email do not reflect decryption.  "OpenPGP encrypted message" and the appropriate button "Decrypt" is presented.  But when the password is entered, the "OpenPGP encrypted message" turns green and the button disappears.  No resulting decryption.

The other issue, is that the Encrypt button does not appear as an option for sending emails to people with keys that are installed.  I can force the button to appear if I choose the defaults of Compose "Sign" and "Encrypt" checked.  This seems to work until the browser is closed.

Unfortunately, it does not appear to actually encrypt the resulting message either way.

I have also tried loading both GnuPG and just using OpenPGP.js alone methodologies (both docker and nextcloud).  Same results.  I have tested with chrome, firefox, and safari on multiple machines.

**Expected behavior**
Entering proper PGP decryption password for stored private key would result in a decrypted message.

**Please complete the following information:**
- Browser: Chromium 107.0.5304.62
- PHP version: 8.0.24 on SM 2.19.4 (nextcloud extension 2.9)
- -PHP version 8.1.11 on SM 2.19.2 (docker)

The docker container was previously working prior to recent upgrades of SnappyMail with GnuPG (my prefered method).  I added GnuPG to my Nextcloud instance as well after running into issues with OpenPGP.js alone.  

It was the recent fix of the Security menu issues that allowed me to start testing PGP in Nextcloud.

I encourage everyone to donate to this project.  I recently did as I appreciate all the work @the-djmaze is putting into it.  SnappyMail is a fantatic addition to Nextcloud and without a doubt my favorite webmail choice.  So glad it's being integrated into Nextcloud.

**Comment by the-djmaze** [comment]
First of all is `Allow OpenPGP` checked in the admin?
![afbeelding](https://user-images.githubusercontent.com/3752035/198869448-7cb50821-33ad-4558-a6ff-7130c41b03d0.png)

**Comment by HeyVern** [comment]
I should have listed all of the above in my original post.  But "yes" to all of the above questions.   Also, of note is that my instance of snappymail in docker was working fine with PGP and has stopped working.  It is exhibiting the same issues as the Nextcloud version of snappymail.   Seems like something has changed.

I also find it strage that snappymail indicates that it has completed the decryption of the message with the appropriate supplied password for the stored private key (as the prompt text turns green), but the resulting message body remain encrypted (not converted to plain text in the browser window).

**Comment by HeyVern** [comment]
@the-djmaze Was this commit part of 2.19.7 release? (I only ask because I am still having same symptoms with PGP as 2.19.6).  Message does not decrypt after successful password for private key entered...just turns green.

**Comment by the-djmaze** [comment]
Well, the problem was with GnuPG encryption.
stream_copy_to_stream() resulted in an empty message, so decryption is successful but results in an empty message.

OpenPGP.js encrypted fine but the signature was wrong due to a double `boundary` parameter in the header.

So, if you still have issues we need to know a couple of things:

1. When encrypt, the password popup shows which is used (OpenPGP.js or GnuPG)
2. When decrypt, the password popup shows which is used (OpenPGP.js or GnuPG)

In case of GnuPG, go to SnappyMail Admin -> About
There it will show a cross or check for GnuPG.
✔ = PHP GnuPG extension is used
❌ = gpg command line is used

Here is also an explanation: https://github.com/the-djmaze/snappymail/wiki/OpenPGP

**Comment by HeyVern** [comment]
Well.
Let's stick with decryption for now, as it is the easiest to test.   I have tested both.  I first installed the private key in OpenPGP.js and got the corrisponding prompt.  Successfully entered the appropriate password for the key.....OpenPGP encrypted message turned green, but email body remained cyphered text.

I then deleted the OpenPGP.js private key, and installed it into GnuPG, resulting the the appropriate prompt....results where the same.  ( I am using command line gpg, not PHP ).

I also tested entering the wrong password for the key and got similar results.  Then I loaded the key into RainLoop's implimentation and used the same test email and corrisponding key/password combination....this produced the desired result.

**Comment by HeyVern** [comment]
@the-djmaze 
^bump

**Comment by HeyVern** [comment]
Just an update: Issue persists in 2.21.1

**Comment by the-djmaze** [comment]
I have updated the demo with a second key.
* 3140898548F06E97 is a RainLoop generated 4096 bit key
* 5F3A5CDC09AD8AE3 is a SnappyMail generated ECC key

Then there are several messages:
* PGP/Inline are RainLoop signed/encrypted send messages (AES)
* PGP/MIME are SnappyMail signed/encrypted send messages (ECC)

Please go ahead and test.
You will notice that when you have both keys installed it becomes an issue.

**Comment by HeyVern** [comment]
- I was able to import the key pair into OpenPGP.js but only the public key into GnuPG.  I **could not** get the private key to **import to GnuPG**.
- PGP Inline Signed and PGP Inline Encrypted worked (with appropriate password and failed on wrong pass as it should)
- PGP / MIME Signed and Encrypted and PGP / MIME Encrypted HTML messages both **failed immediately** on Decrypt button press.  No prompt for key password.

What version is the demo running?  Thanks a bunch for setting up the testing and working on this issue.  Your time is appreciated.

**Comment by the-djmaze** [comment]
Demo is running v2.21.1
Tested browsers:
* Firefox 104.0.2
* Chromium 106

Example `PGP/MIME signed & encrypted HTML message`
![afbeelding](https://user-images.githubusercontent.com/3752035/201686642-87e3f1d3-2d01-46a5-8537-4fa56c5a7d88.png)

![afbeelding](https://user-images.githubusercontent.com/3752035/201686935-9c9ea98c-8e01-4be2-96a1-1ec233a97eee.png)


Example `PGP/Inline encrypted & signed`
![afbeelding](https://user-images.githubusercontent.com/3752035/201687812-13dbd835-ad3d-46db-97cd-55a4a465bec8.png)

![afbeelding](https://user-images.githubusercontent.com/3752035/201687912-56f99cb2-89fe-44c0-9d54-f23605665247.png)


# NOTE
Keep in mind that i have two different keys for the same domain.
The problem here is that the system doesn't know which key to use.
Therefore two options need to be added:
1. Decode `-----BEGIN PGP MESSAGE-----` to find used key (best solution but hard)
2. Provide all possible matched keys and let user choose

**Comment by HeyVern** [comment]
Some progress.  Knowing what you posted above and that the demo was running the same version I was running locally, I set out to test.  I got results that were a bit puzzeling.  The demo worked as expected (with limitations your mentioned above), my local copy did not.  I decided to run through the key generation process on my copy and generated a pair of ECC keys.  I then DELETED the generated keys, and suddenly things started working as they should.  I was able to use the original key pair that I had been testing with previously with success.  I'm not sure what happens during the key generation process, but it appears to have fixed the issue I was dealing with (to reiterate, I didn't actually use the keys that were created, but the generation process somehow addressed the issue in such a way that may previously installed key pair started working).

**Comment by the-djmaze** [comment]
P.S. for the next time: check through shell as `root` user which `gpg-agent` processes are still running.
Can be closed with `gpgconf --kill gpg-agent`

SnappyMail should kill it after use, but this could fail.

Maybe i add `gpg -K` to reload/restart the gpg-agent.
