### ISSUE TITLE
Wrong reaction while typing search phrase in search field.

### ISSUE THREAD

**Issue by gnilebein** [the-djmaze/snappymail#624]
**Describe the bug**
Wrong reaction while typing search phrase in search field.

**To Reproduce**

1. select an email
2. click in search field
3. type the Shift + F

**Expected behavior**
The current message will be forwarded as an attachment.

**Please complete the following information:**
- Browser: Google Chrome
- PHP version: 8.0
- SnappyMail Version: 2.20.0

**Additional context**
This should be examined again which combinations still exist.

**Comment by the-djmaze** [comment]
Shift + F (and any other special combination) do trigger shortcuts.
Just searching for `f` (not capital) works because search is case-insensitive

**Comment by MI-KY** [comment]
From the user perspective this behaviour does not seem to be logical... I think that this is a source for new issues / questions that could be prevented by disabling the shortcuts when the cursor is inside the search field.

To me it seems logical that a SHIFT shortcut does not work when I'm in the search field. Also when I would really try to forward a message I would get a visible feedback (letter F inside the search field). Therefore it should be clear to everyone what is going on...

**Comment by the-djmaze** [comment]
From a user perspective in personally hate Shift+.. for any shortcut.

And there are more conflicts. Take for example Ctrl+F for search.
The browser also uses Ctrl+F and Ctrl+G and /

Either way, any website with shortcuts will have issues one way or another.

I already added special shortcuts, but you need a special keyboard like my Microsoft Natural 4000 keyboard.
It as Fn keys for new, reply, forward, etc. but not all keyboards have these special office keys.

There are already closed issues that solve some shortcuts and i'm open to ditch the RainLoop shortcuts for better ones.

We just need to agree which are the best, are logical and don't conflict too much.

**Comment by MI-KY** [comment]
I see your point, shift isn't the best choice.
Personally the fact that crtl+f often is overwritten drives me crazy, but this is clearly the way how a lot of products work today. So when you hit ctrl+f once you enter into the search mode of the website, hitting it again opens the browser search bar to search inside the website (Firefox at least does so).

There is also an other thing we should think of: the integrations in for example Nextcloud add an other "layer" as hitting ctrl+f first would enter into the Nextcloud unified search bar...

For the shortcuts itself: how about using the same (if possible) as Thunderbird? https://support.mozilla.org/en-US/kb/keyboard-shortcuts-thunderbird

P.S.: sorry while I was writing this, the issue was closed 😉 hope this isn't a problem.

**Comment by the-djmaze** [comment]
I did a commit `Resolved 624` regarding Shift + F, but then GitHub closes the issue.

I reopen this discussion because it is valid and annoying in several ways.

Thunderbird is an option, but what if you use(d) Outlook or Kmail or.... they all use different shortcut keys.

I use KDE and there is a good shortcuts manager. You can create global and scoped shortcuts (just like SnappyMail) and set all the shortcuts you want.
If we have an editor, people can define the shortcuts themselves.

Looking at KMail it uses by default:
```
S = Search
N or -> = Next message
P or <- = Previous message
+ = Next unread message
- = Previous unread message
Strl + N = new message
Shift + N = new message from template
Alt + Q = Focus quick search
R = Reply
Shift + R = Reply without quote
Shift + A = Reply to author
A = Reply to all
Shift + F = Forward as attachment
F = Forward inline
T = Edit as new
Ctrl + R = marks the selected e-mail(s) as read.
Ctrl + U = marks the selected e-mail(s) as unread.
V = View source
Ctrl + S = save message
Del = move to trash
Ctrl + Del = move thread to trash
Shift + Del = delete
Ctrl + Shift + Del = delete thread
Shift + H = Toggle HTML view
```

**Comment by MI-KY** [comment]
Hm, sure it would be the tecnically best solution to be able to modify this shortcuts autonomously 🙂. This maybe would be the cherry on top 😉.

The fact that there are other solutions using other shotcuts is clear a point - I just wanted to say that we could try to use tha same shortcuts as other programs to not reinvent the wheel 😉. With a kind of shortcut manager it would also be possible to have kind of templates (Outlook style, Thunderbird style ecc.).

Is there some specific logic a website has to follow (or must follow as the browser forces it to)? For example: is it possible to hit 3 times ctrl+f in SnappyMail inside of Nextcloud to jump from the unified search to the search bar in Snappy to the search bar of the browser? Or are there only two levels? I ask because if there are multiple "levels" there would exist all the freedom to define a nice presetting of shortcuts - if not we would have to define a preset that is valid for every (or the primary) use case how SnappyMail can be used (standalone, within an integration ecc.).

**Comment by the-djmaze** [comment]
As this is fixed, i've opened a new feature request for the custom shortcuts.
