### ISSUE TITLE
Inline images wrong size

### ISSUE THREAD

**Issue by Parodontitis** [the-djmaze/snappymail#654]
**Describe the bug**
Inline images (base64) will be displayed wit wrong width.

**To Reproduce**
1. Create new mail
2. Copy a picture from other side  (CTRL+c)
3. Paste  the picture in the mail (CTRL+v)

**Expected behavior**
![grafik](https://user-images.githubusercontent.com/41056353/201312670-b59a78c6-bd08-4914-a9f2-b64a9b7a7f0d.png)

**Screenshots**
![grafik](https://user-images.githubusercontent.com/41056353/201312573-33b54f50-a1c8-48a4-b628-eefd908df5d7.png)

Same behavior for received inline pictures.

![grafik](https://user-images.githubusercontent.com/41056353/201313214-d879c105-6420-4154-9d74-efbd1ca08260.png)
(spam message)

**Please complete the following information:**
- Browser: aktuall firefox + chrome
- PHP version: 7.4.30
- SnappyMail Version: 2.20.6

**Comment by the-djmaze** [comment]
How do you copy?

I have a screenshot app and Gimp.
When i copy/paste from them, all works as expected.

**Comment by Parodontitis** [comment]
1. I go to https://www.startpage.com
2. Type in "house" in the search field
3. Switch to category "Images"
4. RM -> Copy Image
5. CTRL+v in snappymail

BUT if I do the same procedure on the google.com page, the image will be copy in the correctly size

![grafik](https://user-images.githubusercontent.com/41056353/201411662-15947cc0-2748-48e3-a778-e4ce1aa58761.png)

Strange...

**Comment by the-djmaze** [comment]
Not strange. Right click with your mouse and choose "inspect element" from the context menu.
There you will see HTML and probably something like ` style=width:100%`

**Comment by Parodontitis** [comment]
You're right. Couldn't you delete the size information automatically when inserting?

**Comment by the-djmaze** [comment]
Not really because you paste HTML, not the image itself.
However, i could do some testing to see if startpage also delivers the blob besides html

**Comment by BiglifeMatt** [comment]
I'm having the same issue with images.  Not only images but if you cut and paste portion of a spreadsheet, it will also stretch all of the columns to fill the width of the email window.  Only see this in SnappyMail... same message opened in RoundCube appear as desired where the image holds the dimensions.

**Comment by BiglifeMatt** [comment]
... also the Nextcloud Mail app it displays properly.

**Comment by the-djmaze** [comment]
Every editor normally is WYSIWYG (what you see is what you get).

But SnappyMail is different.

It tries to "fix" what is broken for responsive view.
An email with table width 1000px doesn't fit on mobile so it makes it `widrh:100%; max-width:1000px`.

The composer on the other hand does not, and tries to be as clean as possible because many CSS and HTML elements are not supported in several mail applications.
So with most WYSIWYG it's more like What You See Is Not What The Recipient Sees.

When pasting code it tries to remove all unsuported data, but somehow it fails.

When i figure it out, it might solve some for you, but not all because someone else might complain the width is gone while it must be there on paste.

Either way, eventually we all might get a common ground solution.

**Comment by the-djmaze** [comment]
I've prioritized image instead of HTML.

And allowed element attributes are listed here: https://github.com/the-djmaze/snappymail/blob/master/dev/External/SquireUI.js#L8

**Comment by the-djmaze** [comment]
This issue is about copy/paste image.

Spreadsheets you should open new issue
