### ISSUE TITLE
Pasted items do not render in original dimensions

### ISSUE THREAD

**Issue by BiglifeMatt** [the-djmaze/snappymail#678]
**Describe the bug**
Images that are copied and pasted, or dragged into the email body or even email signature from another email app, such as Gmail, can distort when they are opened by Snappymail.  

Images that are pasted or dragged into Snappymail to be sent, it will insert the image at full resolution.

If a selection of a spreadsheet is hightlighted and copied and pasted into another app like Gmail, then opened by Snappymail, the pasted selection displays as a single pixel vertical line for the length of the pasted selection.

**Expected behavior**
A fixed resolution image of pasted objects.

**Please complete the following information:**
- Browser: Chrome, Edge, Brave
- IMAP daemon: dovecot (iRedMail)
- PHP version: 7.4
- SnappyMail Version: 2.21.2

**Comment by the-djmaze** [comment]
Scaling images can be added, but how?
1. Should it resize the image so that you don't send 20MiB email?
2. Should it just set width/height and send 20MiB email?
3. Should it compress the .svg to .svgz?

Spreadsheets:
Each application generates HTML in its own way.
LibreOffice, Microsoft Excel, Office365, Gsuite, etc. etc.
How should SnappyMail fix them so that it is also properly visible on small devices like mobile phones?

Not to mention the differences how each browser handles copy/paste.
Some copy raw, some integrate the whole CSS style in the `style=""` attribute.

The web is a mess, so please provide examples what you exactly copy, from where and the result HTML.

Else i just shoot in the dark.

**Comment by BiglifeMatt** [comment]
Let's start with the image in the body.  I'll attach three images here.

The first is an image that is 1080x1440.

This is it when it is pasted into Gmail to send to dovecot server.
![Gmail image sent to Snappymail](https://user-images.githubusercontent.com/93135814/202028625-3df6003e-dc5f-479d-aa54-4a097ff94a72.jpg)

This is the image of the email opened in Roundcube.
![Image sent from Gmail opened in Roundcube](https://user-images.githubusercontent.com/93135814/202028739-e2bef6a6-a51a-4c39-a30a-067e96ace611.jpg)

This is the image of the email opened in Snappymail.
![Image sent from Gmail opened in Snappymail](https://user-images.githubusercontent.com/93135814/202028817-3a2bf1e2-fbff-4ee3-9ac9-95e4eceeb90a.jpg)

This is the image if it is pasted into Snappymail.  
![Image pasted in Snappymail](https://user-images.githubusercontent.com/93135814/202029438-f856b7a6-282e-45e9-acd3-e5419130e804.jpg)

**Comment by the-djmaze** [comment]
Ok i will send myself an email with large image from gmail to snappy and see what happens.

Paste image in SnappyMail is indeed as-is because the image is very large.
Some browsers you can click the image and resize it.
Some browsers don't support image resize.
Maybe add a style editor to compose window?

**Comment by the-djmaze** [comment]
Works now responsive.
Thanks for finding this issue!

https://user-images.githubusercontent.com/3752035/202043277-f069b7d1-54c7-457f-95a8-ec7d1f7c3d3d.mp4

**Comment by BiglifeMatt** [comment]
Thank you.  This helps correct mail sent to me.  However, is there a way to also control the size of an image that I would bring in if I use the inline insert via the folder icon on the HTML editor bar?  It just inserts as full size still.

**Comment by the-djmaze** [comment]
#262 is the request for image resizing
