### ISSUE TITLE
Searching for tags does not replace variable name

### ISSUE THREAD

**Issue by Niveshkrishna** [the-djmaze/snappymail#738]
**Describe the bug**

When performing search operation on emails, there's an option to search by tags. After selecting from a list of predefined tags the variable name is displayed in search box instead of tag name

**To Reproduce**
1. Go to https://snappymail.eu/demo/#/mailbox/INBOX
2. Click on More search button
3. Select a tag from list of predefined  and hit search
4. See that text in search box says keyword=$label1

Note that it works perfectly fine with custom tags

**Expected behavior**

Show the value of $label1

**Screenshots**

![image](https://user-images.githubusercontent.com/16881005/205362637-5191d899-ed8d-44ef-8fda-af7639423a2e.png)

**Please complete the following information:**
- Browser: [e.g. chromium 100, firefox 100, safari 14, mobile]
- IMAP daemon: [e.g. courier, dovecot]
- PHP version:
- SnappyMail Version:

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Place them here (few lines) or as attachments (many lines)

**Additional context**

**Comment by the-djmaze** [comment]
Correct. Problem is that Thunderbird has this behavior.
Instead of just using "Important" it uses $label1 and translate that in each language.

SnappyMail does the same for the Thunderbird tags, but does not for everything else you define.

If we set the search `keyword=$label1` as `keyword=important` then this would be the tag `important` and not `$label1`.
Therefore we can't change that because there is no way SnappyMail can decide what you are searching (in any language).
