### ISSUE TITLE
[Feature Request] Add a way to provide separate SMTP username and password

### ISSUE THREAD

**Issue by yogi81** [the-djmaze/snappymail#814]
I have different username and password combinations for IMAP and SMTP.

Right now snappymail is using same username and password combination for IMAP and SMTP authentication and there is no way to define a separate username and password in the admin interface nor the system is asking for a different username and password when sending email, when SMTP authentication fails.

**Comment by the-djmaze** [comment]
Since more people have this issue, i have an idea for this.

At Admin -> Domains -> Domain -> SMTP add a setting 'ask credentials'.
Then when you send your first message, it will ask for them.

On logout/switch account the credentials are gone and next time it will ask them again.

It could also be possible to store the credentials so that it will not ask again.

Which do you prefer?

**Comment by the-djmaze** [comment]
Also read #431 and #458

**Comment by yogi81** [comment]
thanks! I will try to use Override SMTP plugin.
