### ISSUE TITLE
Text formatting menus overlaps other butons on mobile

### ISSUE THREAD

**Issue by Cwpute** [the-djmaze/snappymail#828]
When writing an email on mobile, with the keyboard open, the text formatting menu can be pushed up above other menus like so: 
![snappy phone](https://user-images.githubusercontent.com/80604512/210560025-6521dd36-d058-41ee-a6d7-3356044ff791.png)
It should probably not do that, as it prevents from using hidden butons unless you hide your keyboard

**Please complete the following information:**
- Keyboard app: AnySoftKeyboard (https://github.com/AnySoftKeyboard/AnySoftKeyboard)
- Browser: einkbro (https://github.com/plateaukao/einkbro)
- IMAP daemon: unknown
- PHP version: unknown
- SnappyMail Version: latest

**Comment by the-djmaze** [comment]
The problem with mobile is that:
- Some keyboards overlap the bottom of the browser window #686 so placing the buttons at the bottom has an issue (hidden).
- Keeping the buttons fixed will make the content area very small.

So instead of putting the buttons at bottom or fixed, they float at the top.
Sure they overlap other buttons/functionality but at least you can now hide buttons bar by closing the keyboard.
Currently this is the least annoying way to my knowledge.

If you have a better idea we can try it out.

**Comment by Cwpute** [comment]
I can see two possible workarounds:

1. On my screenshot there is plenty of unused space between the keyboard and and the actual text area because the message is presented as a popu-up window rather than fullscreen. Maybe turning the New Mail window fullscreen could help gain enough space to prevent this behavior ?

2. Alternatively, `To:` `From:` and `Subject:` text fields could be hidden when typing in the body of the mail. Often times you've already entered those before writing the rest. These text fields could still be accessed through a button perhaps (least favourite option), by simply scrolling upwards, or hiding the keyboard (both quite natural i think).

**Comment by the-djmaze** [comment]
With v2.25 the size of the compose window should be larger now as i completely changed the layout behavior (no fixed/absolute positioning).
This should solve some issues so we can now improve the formatting menu design and think of better solutions.
