### ISSUE TITLE
Saving sieve filters of one account can override filters of other account

### ISSUE THREAD

**Issue by SelfRef** [the-djmaze/snappymail#892]
**Describe the bug**
The easiest way for me for modifying existing filters is to open mail view in one tab and filters in other tab. As long as only one account is used everything works as expected - I can browse mails, copy subjects/addresses and paste them in filter settings on the second tab and save them.

I have two accounts connected in SnappyMail - for private use and for work, both have sieve filters. Today while changing filters I accidentally switched to work account on first tab and didn't switch on second tab, then I saved filters on second tab and all my personal filters have been overwritten with the ones from work account. I realized that after a while because no error was thrown.

**To Reproduce**
1. Have two separate mail accounts configured with filters enabled
2. Switch to the first account using a menu in the top-right corner
3. Duplicate tab (now you have second view of first account)
4. In the second tab go to settings and open sieve filters
5. Go to first tab and switch to the second account using account selector
6. Go to second tab and save filters

**Expected behavior**
Filters of second account are saved to second account (or error is thrown).

**Actual behavior**
Filters of second account are saved to first account irreversibly. Now both accounts have same filters.

**Please complete the following information:**
- Browser: Firefox 109.0
- PHP version: 8.1.13
- Nextcloud version: 25.0.3 (official docker image)
- SnappyMail Version: 2.25.0 (from Nextcloud appstore)

**Additional context**
The issue seems to be reproducible and I suspect it has to do something with session state - as I change active account in one tab, the second tab inherits this change and saves filters to active account.

I consider this kind of niche test-case but still a bug that can happen in the future (to me for sure).

**Comment by the-djmaze** [comment]
SnappyMail should not be run in 2 tabs.

I will think about a way to block any access using multiple tabs.

**Comment by phsc84** [comment]
> SnappyMail should not be run in 2 tabs.
> 
> I will think about a way to block any access using multiple tabs.

Please not. Sometimes it is quite handy to have one mail open whilst writing another one.

**Comment by SelfRef** [comment]
Also some solution for modifying filters without a need to go to the settings would be nice as a feature to add to the roadmap for future. Like a panel or dialog on top of the mail list.

**Comment by the-djmaze** [comment]
I understand you both.

There are several things in play here.
When you have a tab open it does several interval requests to the server:
* it asks every 5 minutes the status of each IMAP mailbox (folder) and fetch new mails.
* If you add/delete a mailbox/message the other tab doesn't know
* if you label/flag/tag a message the other tab must reload all messages
* if you move a message the other tab must reload the messagelist
* etc. etc.

This would add a double strain on the server and could cause out-of-sync data because the cache is also not aware of (dead)locking.

This all could be prevented with rotating tokens and other, but 1 tab can't communicate with the other browser tab.

RainLoop did put login data in the URL but that can't be larger then 4kb and some login tokens are longer then 4kb (there's a reported issue and solved with multi cookie).

Instead of using cookies we could use a short tab token that is added to each request. But if the token is gone, you must login again, and that makes some url's difficult to handle.

Another option could be to use websockets, but then people need special server setups to handle the `wss://....` requests.
There's already a "big-pipe" stream for contacts synchronisation, but that also fails on certain HTTPD setups.

I've already said in a few other issues of people who requested some features for multiple tabs that it is almost not possible.

It's not impossible, but i wonder if SnappyMail should support it and how on earth to solve the issues.

**Comment by the-djmaze** [comment]
As a result, for now i think it's best to have an `id` with each action to know which account is logged in.
If the id does not match with the received login, it should fail.

Later on the id could be the login data in some way.

**Comment by phsc84** [comment]
This sounds like a good solution (at least in my eyes)! Thanks!

**Comment by SelfRef** [comment]
Yeah, it looks like a good solution for accidental requests between two accounts. Till yesterday I used only the same account in both tabs and my issue was caused by my mistake as I forgot to refresh the second tab after account switch.

**Comment by the-djmaze** [comment]
Good.
I've also protected the GET requests, so this should be it for now then.
