### ISSUE TITLE
Upgrade from Rainloop,  password not migrated

### ISSUE THREAD

**Issue by mmallejac** [the-djmaze/snappymail#898]
**SnappyMail 2.25.1 within Nexctloud 25.0.3, Firefox latest**

Hello !

I am about to migrate several servers with Nextcloud 24 and Rainloop to Nextcloud 25 and Snappymail. I have done already two of them, and met the same difficulty : I have to put back the email password(s) within Snappymail for each user.

Once updated to Nextcloud 25, I've added the Snappymail app, used the Import RainLoop data option, seen that many things have been imported, great. Entering Snappymail asked my main mail password (and then the same for each mail accounts).
The other stuff - mail accounts, signature and so on - were correctly imported.
Did I miss something ?

Also a question : is your "Nextcloud file picker" part of Snappymail or does it use an external project ? We have an Nextcloud app project that would require such object.

Many thanks in advance,
Michel

**Comment by the-djmaze** [comment]
> Entering Snappymail asked my main mail password

The above commit might help to solve this migration

>  (and then the same for each mail accounts).
> The other stuff - mail accounts, signature and so on - were correctly imported.
Did I miss something ?

Yes, the RainLoop additional accounts are encrypted with APP_SALT.
SnappyMail does NOT do this because of an issue i reported to RainLoop
https://github.com/RainLoop/rainloop-webmail/issues/2134
SnappyMail can read the passwords, but it can't encrypt them.
Therefore it asks for the passwords.

> Also a question : is your "Nextcloud file picker" part of Snappymail or does it use an external project ? We have an Nextcloud app project that would require such object.
Yes it is part of Snappymail and you can find the related code here:
https://github.com/the-djmaze/snappymail/blob/8cf8823d562970ea06f4a81090792876c679f2dd/plugins/nextcloud/js/webdav.js#L73

**Comment by mmallejac** [comment]
Many thanks ! 
Any idea when this commit will be released in a version ?

**Comment by the-djmaze** [comment]
https://apps.nextcloud.com/apps/snappymail

**Comment by negati0ns** [comment]
Many thanks.  Fix applied.
