### ISSUE TITLE
Sep boxes showing up in certain emails

### ISSUE THREAD

**Issue by Zero3K** [the-djmaze/snappymail#900]
Boxes with the word Sep are showing up in certain emails. A screenshot of such email and its source are included.

![Sep Boxes in Email](https://user-images.githubusercontent.com/6194332/216377889-83c82d68-1785-4aba-b6f0-a5157d736b47.png)
[Revolut Email Source.txt](https://github.com/the-djmaze/snappymail/files/10570906/Revolut.Email.Source.txt)

**Comment by Zero3K** [comment]
Will you fix it or not?

**Comment by the-djmaze** [comment]
That is a very difficult question.

The sender screwed up the email because someone decided that the unicode character LSEP is cool.
And when you look at the Unicode table, there are so many characters your browser can't render that making a filter for all o them makes the JavaScript twice as big.

Only filtering control characters using `\pC` would solve the LSEP issue, but then others l8ke \r, \n, \t, etc. are also removed.

It would be better they fix their code as many other mail clients could show the same issue.

**Comment by Zero3K** [comment]
Getting them to fix it seems impossible.

**Comment by Zero3K** [comment]
https://stackoverflow.com/a/59360476/8067355

**Comment by the-djmaze** [comment]
But they advice to replace it with `<br>` but that makes the sentence very weird:

```
How 

to find...
```

Replacing with a space makes it better for this situation.
But what if someone else uses the LSEP as intended  break, then there is no break.
Doing nothing shows the weird character, but then the person who wrote the mail at least knows it screwed up.

So what should we do?

**Comment by Zero3K** [comment]
![image](https://user-images.githubusercontent.com/6194332/216434795-b16c49f1-daf9-4194-9776-56afcb046e89.png)

**Comment by the-djmaze** [comment]
My first link also says it's a Chrome thing 😉

**Comment by Zero3K** [comment]
Maybe do it per domain?

**Comment by Zero3K** [comment]
> My first link also says it's a Chrome thing 😉

I was just showing that it is not a line break in this case.

**Comment by Zero3K** [comment]
> Maybe do it per domain?

Doing it that way makes sense to me.

**Comment by Zero3K** [comment]
Why not do it depending on the domain of the email's address?

**Comment by the-djmaze** [comment]
> Why not do it depending on the domain of the email's address?

There are a trillion domains and each day more.
Also mails can be forwarded/moved to other  mailboxes or as attachments.
It's all or nothing.
