### ISSUE TITLE
OpenPGP Keys lost on fresh session

### ISSUE THREAD

**Issue by TheCuteFoxxy** [the-djmaze/snappymail#973]
**Describe the bug**
Encryption keys are cleared when the browser cache is cleared or when used in an incognito tab regardless of store and backup settings.

**To Reproduce**
1. Login to Snappymail via regular browsing window (not private)
2. Select Generate a key pair with OpenPGP.js
3. Select all backup and store options during the generation
4. Generate key pair
5. Confirm key generation for both public and private keys
6. Open an incognito/private window
7. Login to Snappymail
8. Check public/private key list for OpenPGP.js
9. Observe missing keys

**Expected behavior**
Keys persist in Snappymail regardless of cache when store and backup options are selected

**Screenshots**
Generate Key Pair completed form
![https://cdn.thecutefoxxy.com/AZoMzF.png](https://cdn.thecutefoxxy.com/AZoMzF.png)

Resulting Key Pair
![https://cdn.thecutefoxxy.com/9XXUmP.png](https://cdn.thecutefoxxy.com/9XXUmP.png)

Missing Keys
![https://cdn.thecutefoxxy.com/1GwBFY.png](https://cdn.thecutefoxxy.com/1GwBFY.png)

**Please complete the following information:**
- Browser: Firefox 109.0
- IMAP daemon: Unknown
- PHP version: 7.4.33
- SnappyMail Version: 2.25.4

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Not sure which logs are needed, if any, let me know and I will attach.

**Additional context**

**Comment by the-djmaze** [comment]
Correct. Keys stored on server are not loaded in OpenPGP.js
The problem is that private keys on server are passphrase protected and can't be loaded automatically.
It is also not mentioned in #89

The settings page could have enhancements in the OpenPGP.js section
1. "Import public keys from GnuPG" checkbox
2. "Import private keys from GnuPG" checkbox (asks password for each)
3. "Import public keys from backup" checkbox
4. "Import private keys from backup" checkbox

The settings page could also have a new section named "Backup"

**Comment by TheCuteFoxxy** [comment]
Private keys I can understand due to the additional authentication step, this issue affects all keys including the public. Is there a way to prevent average users from accidentally clearing their keys? (Meaning users who wouldn't have a regular reason to start fresh sessions). 

Is there an expiration time that can be modified to prevent a natural decay of the keys or would this only occur when a fresh session is forced for the browser?

**Comment by the-djmaze** [comment]
> Is there a way to prevent average users from accidentally clearing their keys?

No, users should always manage that themselves.
How else could they use the keys in other applications?
Same rules apply as for your other password, pin, totp, etc. management.

**Comment by the-djmaze** [comment]
OpenPGP.js doesn't require keys when GnuPG works and has keys.
SnappyMail then just sign, verify, encrypt and decrypt on the server (easy when using multiple browsers and as benefit the attachments are encrypted).

If you don't trust the server, then the only problem is sign and decrypt because they use private keys.
So i will improve the generate key dialog that it will provide the private key as download.

**Comment by the-djmaze** [comment]
Next release will have many improvements regarding key handling.
It also has an "import from server" button to load the keys in OpenPGP.

![afbeelding](https://github.com/the-djmaze/snappymail/assets/3752035/66ffb721-bb3a-4c48-87bb-2ed48fcbda4c)
