### ISSUE TITLE
Upgrade to Squire 2.0.1

### ISSUE THREAD

**Issue by phsc84** [the-djmaze/snappymail#978]
SnappyMail still uses Squire 1.11.3 but some days ago Squire 2.0.1 was released. Maybe it is worth to consider an upgrade.
https://github.com/fastmail/Squire/tree/master/dist

**Comment by the-djmaze** [comment]
Squire 2.0 is almost the same as 1.11.
The difference is that it is converted to typescript (yes it is a hype, same result).
Also Squire 2.0 almost has all the changes i requested with PR's for 1.11

So basically speaking the modified Squire that is used by SnappyMail is even 2.1 or 3.0.
Now with SnappyMail 2.26.2 Squire can handle 2MB+ HTML with ease due to a solved bug.

I do keep track of the Squire project but not intending to switch due to the changes i made for a better experience.

**Comment by Zero3K** [comment]
How about sending the improvements you made to him? Unless he doesn't think they are good enough.

**Comment by the-djmaze** [comment]
> How about sending the improvements you made to him? Unless he doesn't think they are good enough.

I did, that's why there's 2.0 now.
