### ISSUE TITLE
unique attachments.zip filename

### ISSUE THREAD

**Issue by Nono-m0le** [the-djmaze/snappymail#992]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I download the 'attachments.zip' because it has the same name and I end-up with many same-looking files, without be able to differenciate them.

**Describe the solution you'd like**
Ideally, some name like `YYYYMMDD_email_titles.zip` (ex: `20230225_Picture_of_the_kids.zip`) would be perfect, but `timestamp_snappymail.zip` would honestly also do the job ...

**Comment by the-djmaze** [comment]
I understand your frustration caused by your browser.

I've changed the setting in my browser to always ask where to save downloads.
So i can place them where i want and with the name i want.

SnappyMail could remove your frustration a bit, but not the frustrations you have on other websites.
Best is just to change your browser behavior (as a lot of people complained when Firefox change it).

Else i will look if i can make some people hapier (but not all as everyone wants to name their downloads differently).
For example i also like to place the attachments in a folder for a specific project or sender name or...

**Comment by Nono-m0le** [comment]
Thanks !
I actually already changed the behavior, but still by default the name remains the same which is frustrating :)

**Comment by the-djmaze** [comment]
Then i will figure something out

**Comment by Nono-m0le** [comment]
Thanks @the-djmaze !
Will it be available in v2.26.5 soon or shall I try to clone the repo ?

**Comment by the-djmaze** [comment]
Next release  within 2 weeks.

I'm working on some @media queries vor PWA and fullscreen mode
